// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/Jim3Things/CloudChamber/pkg/protos/Stepper/stepper.proto

package Stepper

import (
	context "context"
	fmt "fmt"
	common "github.com/Jim3Things/CloudChamber/pkg/protos/common"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Define the various simulated time stepping policies
type StepperPolicy int32

const (
	// Default value, indicates an uninitialized stepper
	StepperPolicy_Invalid StepperPolicy = 0
	// Policy that immediately moves the simulated time forward with any
	// wait operation.  Useful for shortening test runs.
	StepperPolicy_NoWait StepperPolicy = 1
	// Policy that magnifies time, but still proceeds forward automatically.
	// This option requires a delay per tick to determine how fast time runs
	StepperPolicy_Measured StepperPolicy = 2
	// Policy that requires manual stepping of time.  Simulated time only
	// moves forward as a result of an externally generated step command.
	StepperPolicy_Manual StepperPolicy = 3
)

var StepperPolicy_name = map[int32]string{
	0: "Invalid",
	1: "NoWait",
	2: "Measured",
	3: "Manual",
}

var StepperPolicy_value = map[string]int32{
	"Invalid":  0,
	"NoWait":   1,
	"Measured": 2,
	"Manual":   3,
}

func (x StepperPolicy) String() string {
	return proto.EnumName(StepperPolicy_name, int32(x))
}

func (StepperPolicy) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fd4a41c05ff9560e, []int{0}
}

// Define the parameters to a stepper policy request parameters
type PolicyRequest struct {
	// Required policy
	Policy StepperPolicy `protobuf:"varint,1,opt,name=policy,proto3,enum=stepper.StepperPolicy" json:"policy,omitempty"`
	// Number of seconds between ticks.  Only valid for the "Measured" policy.
	MeasuredDelay        *duration.Duration `protobuf:"bytes,2,opt,name=measuredDelay,proto3" json:"measuredDelay,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *PolicyRequest) Reset()         { *m = PolicyRequest{} }
func (m *PolicyRequest) String() string { return proto.CompactTextString(m) }
func (*PolicyRequest) ProtoMessage()    {}
func (*PolicyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd4a41c05ff9560e, []int{0}
}

func (m *PolicyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PolicyRequest.Unmarshal(m, b)
}
func (m *PolicyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PolicyRequest.Marshal(b, m, deterministic)
}
func (m *PolicyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PolicyRequest.Merge(m, src)
}
func (m *PolicyRequest) XXX_Size() int {
	return xxx_messageInfo_PolicyRequest.Size(m)
}
func (m *PolicyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PolicyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PolicyRequest proto.InternalMessageInfo

func (m *PolicyRequest) GetPolicy() StepperPolicy {
	if m != nil {
		return m.Policy
	}
	return StepperPolicy_Invalid
}

func (m *PolicyRequest) GetMeasuredDelay() *duration.Duration {
	if m != nil {
		return m.MeasuredDelay
	}
	return nil
}

// Define the parameters when requesting a delay
type DelayRequest struct {
	// The minimum simulated time before the delay is completed.
	AtLeast *common.Timestamp `protobuf:"bytes,1,opt,name=atLeast,proto3" json:"atLeast,omitempty"`
	// An additional maximum number of ticks that can be added to the delay.
	// A random number of ticks [0-jitter) are added to the delay time.  This
	// is to simulate the random delays seen in, e.g., disk I/O or network
	// communications.
	Jitter               int64    `protobuf:"varint,2,opt,name=jitter,proto3" json:"jitter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelayRequest) Reset()         { *m = DelayRequest{} }
func (m *DelayRequest) String() string { return proto.CompactTextString(m) }
func (*DelayRequest) ProtoMessage()    {}
func (*DelayRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd4a41c05ff9560e, []int{1}
}

func (m *DelayRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelayRequest.Unmarshal(m, b)
}
func (m *DelayRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelayRequest.Marshal(b, m, deterministic)
}
func (m *DelayRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelayRequest.Merge(m, src)
}
func (m *DelayRequest) XXX_Size() int {
	return xxx_messageInfo_DelayRequest.Size(m)
}
func (m *DelayRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DelayRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DelayRequest proto.InternalMessageInfo

func (m *DelayRequest) GetAtLeast() *common.Timestamp {
	if m != nil {
		return m.AtLeast
	}
	return nil
}

func (m *DelayRequest) GetJitter() int64 {
	if m != nil {
		return m.Jitter
	}
	return 0
}

func init() {
	proto.RegisterEnum("stepper.StepperPolicy", StepperPolicy_name, StepperPolicy_value)
	proto.RegisterType((*PolicyRequest)(nil), "stepper.PolicyRequest")
	proto.RegisterType((*DelayRequest)(nil), "stepper.DelayRequest")
}

func init() {
	proto.RegisterFile("github.com/Jim3Things/CloudChamber/pkg/protos/Stepper/stepper.proto", fileDescriptor_fd4a41c05ff9560e)
}

var fileDescriptor_fd4a41c05ff9560e = []byte{
	// 391 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0xc1, 0x4e, 0xdb, 0x40,
	0x10, 0xad, 0x93, 0xd6, 0x6e, 0x27, 0x49, 0xe5, 0xae, 0xd4, 0x28, 0x4d, 0xa5, 0x2a, 0xca, 0x29,
	0x6a, 0xa5, 0xdd, 0xe2, 0x08, 0x38, 0x70, 0x40, 0x4a, 0xc2, 0x01, 0x44, 0x22, 0xe4, 0x44, 0x42,
	0xe2, 0xb6, 0x8e, 0x17, 0x67, 0xc1, 0xeb, 0x35, 0xf6, 0x1a, 0x94, 0x1b, 0xff, 0xca, 0x8f, 0xa0,
	0xd8, 0x6b, 0x20, 0x84, 0x1c, 0xe0, 0x64, 0xcf, 0xbc, 0x37, 0x6f, 0xde, 0x3c, 0x1b, 0x86, 0x01,
	0x57, 0x8b, 0xcc, 0xc3, 0x73, 0x29, 0xc8, 0x09, 0x17, 0xfd, 0xd9, 0x82, 0x47, 0x41, 0x4a, 0x86,
	0xa1, 0xcc, 0xfc, 0xe1, 0x82, 0x0a, 0x8f, 0x25, 0x24, 0xbe, 0x0e, 0x48, 0x9c, 0x48, 0x25, 0x53,
	0x32, 0x55, 0x2c, 0x8e, 0x59, 0x42, 0xd2, 0xe2, 0x89, 0xf3, 0x36, 0xb2, 0x74, 0xd9, 0x1e, 0xbd,
	0x4f, 0x6d, 0x2e, 0x85, 0x90, 0x11, 0x51, 0x5c, 0xb0, 0x54, 0x51, 0x11, 0x17, 0x72, 0xed, 0xdf,
	0x81, 0x94, 0x41, 0xc8, 0x0a, 0x96, 0x97, 0x5d, 0x12, 0x26, 0x62, 0xb5, 0xd4, 0xe0, 0x9f, 0xd7,
	0xa0, 0x9f, 0x25, 0x54, 0x71, 0x19, 0x15, 0x78, 0xf7, 0xde, 0x80, 0xc6, 0x99, 0x0c, 0xf9, 0x7c,
	0xe9, 0xb2, 0x9b, 0x8c, 0xa5, 0x0a, 0x61, 0x30, 0xe3, 0xbc, 0xd1, 0x32, 0x3a, 0x46, 0xef, 0xbb,
	0xd3, 0xc4, 0xa5, 0x7b, 0x7d, 0x8d, 0xa6, 0x6b, 0x16, 0x3a, 0x84, 0x86, 0x60, 0x34, 0xcd, 0x12,
	0xe6, 0x8f, 0x58, 0x48, 0x97, 0xad, 0x4a, 0xc7, 0xe8, 0xd5, 0x9c, 0x5f, 0xb8, 0xd8, 0x8c, 0xcb,
	0xcd, 0x78, 0xa4, 0x37, 0xbb, 0xeb, 0xfc, 0xee, 0x14, 0xea, 0xf9, 0x4b, 0x69, 0xe0, 0x1f, 0x58,
	0x54, 0x9d, 0x32, 0x9a, 0xaa, 0xdc, 0x41, 0xcd, 0xf9, 0x81, 0x8b, 0xcb, 0xf1, 0xac, 0xbc, 0xdc,
	0x2d, 0x19, 0xa8, 0x09, 0xe6, 0x15, 0x57, 0x8a, 0x25, 0xf9, 0xda, 0xaa, 0xab, 0xab, 0xbf, 0x03,
	0x68, 0xac, 0xd9, 0x45, 0x35, 0xb0, 0x8e, 0xa3, 0x5b, 0x1a, 0x72, 0xdf, 0xfe, 0x84, 0x00, 0xcc,
	0x89, 0x3c, 0xa7, 0x5c, 0xd9, 0x06, 0xaa, 0xc3, 0xd7, 0xb1, 0xf6, 0x63, 0x57, 0x56, 0xc8, 0x98,
	0x46, 0x19, 0x0d, 0xed, 0xaa, 0xf3, 0x60, 0x80, 0xa5, 0x45, 0xd0, 0x01, 0x7c, 0x9b, 0x32, 0xa5,
	0xb5, 0x9e, 0x23, 0x59, 0x8b, 0xae, 0xdd, 0xdc, 0xb8, 0xf9, 0x68, 0xf5, 0x29, 0xd0, 0x1e, 0x7c,
	0x5e, 0xe9, 0xa0, 0x2d, 0xf8, 0xd6, 0xb9, 0xff, 0x50, 0x9d, 0xc8, 0xbb, 0xad, 0x63, 0x9b, 0xb9,
	0xa0, 0x1d, 0xf8, 0x92, 0x67, 0x89, 0x7e, 0x3e, 0x59, 0x7c, 0x99, 0xed, 0x1b, 0x23, 0x83, 0xfd,
	0x8b, 0xdd, 0x0f, 0xfd, 0xd4, 0x9e, 0x99, 0xd7, 0xfd, 0xc7, 0x00, 0x00, 0x00, 0xff, 0xff, 0x47,
	0xe3, 0x31, 0x83, 0x14, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StepperClient is the client API for Stepper service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StepperClient interface {
	// Set the stepper's policy governing the rate and conditions
	// for the simulated time to move forward.
	SetPolicy(ctx context.Context, in *PolicyRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// When the stepper policy is for manual single-stepping, this
	// function forces a single step forward in simulated time.
	Step(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
	// Get the current simulated time.
	Now(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*common.Timestamp, error)
	// Delay the simulated time by a specified amount +/- an allowed variance.
	// Do not return until that new time is current.
	Delay(ctx context.Context, in *DelayRequest, opts ...grpc.CallOption) (*common.Timestamp, error)
}

type stepperClient struct {
	cc *grpc.ClientConn
}

func NewStepperClient(cc *grpc.ClientConn) StepperClient {
	return &stepperClient{cc}
}

func (c *stepperClient) SetPolicy(ctx context.Context, in *PolicyRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/stepper.Stepper/SetPolicy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stepperClient) Step(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/stepper.Stepper/Step", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stepperClient) Now(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*common.Timestamp, error) {
	out := new(common.Timestamp)
	err := c.cc.Invoke(ctx, "/stepper.Stepper/Now", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stepperClient) Delay(ctx context.Context, in *DelayRequest, opts ...grpc.CallOption) (*common.Timestamp, error) {
	out := new(common.Timestamp)
	err := c.cc.Invoke(ctx, "/stepper.Stepper/Delay", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StepperServer is the server API for Stepper service.
type StepperServer interface {
	// Set the stepper's policy governing the rate and conditions
	// for the simulated time to move forward.
	SetPolicy(context.Context, *PolicyRequest) (*empty.Empty, error)
	// When the stepper policy is for manual single-stepping, this
	// function forces a single step forward in simulated time.
	Step(context.Context, *empty.Empty) (*empty.Empty, error)
	// Get the current simulated time.
	Now(context.Context, *empty.Empty) (*common.Timestamp, error)
	// Delay the simulated time by a specified amount +/- an allowed variance.
	// Do not return until that new time is current.
	Delay(context.Context, *DelayRequest) (*common.Timestamp, error)
}

// UnimplementedStepperServer can be embedded to have forward compatible implementations.
type UnimplementedStepperServer struct {
}

func (*UnimplementedStepperServer) SetPolicy(ctx context.Context, req *PolicyRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetPolicy not implemented")
}
func (*UnimplementedStepperServer) Step(ctx context.Context, req *empty.Empty) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Step not implemented")
}
func (*UnimplementedStepperServer) Now(ctx context.Context, req *empty.Empty) (*common.Timestamp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Now not implemented")
}
func (*UnimplementedStepperServer) Delay(ctx context.Context, req *DelayRequest) (*common.Timestamp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delay not implemented")
}

func RegisterStepperServer(s *grpc.Server, srv StepperServer) {
	s.RegisterService(&_Stepper_serviceDesc, srv)
}

func _Stepper_SetPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StepperServer).SetPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stepper.Stepper/SetPolicy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StepperServer).SetPolicy(ctx, req.(*PolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stepper_Step_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StepperServer).Step(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stepper.Stepper/Step",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StepperServer).Step(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stepper_Now_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StepperServer).Now(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stepper.Stepper/Now",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StepperServer).Now(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stepper_Delay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StepperServer).Delay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stepper.Stepper/Delay",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StepperServer).Delay(ctx, req.(*DelayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Stepper_serviceDesc = grpc.ServiceDesc{
	ServiceName: "stepper.Stepper",
	HandlerType: (*StepperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetPolicy",
			Handler:    _Stepper_SetPolicy_Handler,
		},
		{
			MethodName: "Step",
			Handler:    _Stepper_Step_Handler,
		},
		{
			MethodName: "Now",
			Handler:    _Stepper_Now_Handler,
		},
		{
			MethodName: "Delay",
			Handler:    _Stepper_Delay_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/Jim3Things/CloudChamber/pkg/protos/Stepper/stepper.proto",
}
