// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: github.com/Jim3Things/CloudChamber/pkg/protos/Stepper/stepper.proto

package Stepper

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// define the regex for a UUID once up-front
var _stepper_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on PolicyRequest with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *PolicyRequest) Validate() error {
	if m == nil {
		return nil
	}

	if _, ok := _PolicyRequest_Policy_InLookup[m.GetPolicy()]; !ok {
		return PolicyRequestValidationError{
			field:  "Policy",
			reason: "value must be in list [1 2 3]",
		}
	}

	if v, ok := interface{}(m.GetMeasuredDelay()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return PolicyRequestValidationError{
				field:  "MeasuredDelay",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// PolicyRequestValidationError is the validation error returned by
// PolicyRequest.Validate if the designated constraints aren't met.
type PolicyRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PolicyRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PolicyRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PolicyRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PolicyRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PolicyRequestValidationError) ErrorName() string { return "PolicyRequestValidationError" }

// Error satisfies the builtin error interface
func (e PolicyRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPolicyRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PolicyRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PolicyRequestValidationError{}

var _PolicyRequest_Policy_InLookup = map[StepperPolicy]struct{}{
	1: {},
	2: {},
	3: {},
}

// Validate checks the field values on DelayRequest with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *DelayRequest) Validate() error {
	if m == nil {
		return nil
	}

	if v, ok := interface{}(m.GetAtLeast()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DelayRequestValidationError{
				field:  "AtLeast",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetJitter() < 0 {
		return DelayRequestValidationError{
			field:  "Jitter",
			reason: "value must be greater than or equal to 0",
		}
	}

	return nil
}

// DelayRequestValidationError is the validation error returned by
// DelayRequest.Validate if the designated constraints aren't met.
type DelayRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DelayRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DelayRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DelayRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DelayRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DelayRequestValidationError) ErrorName() string { return "DelayRequestValidationError" }

// Error satisfies the builtin error interface
func (e DelayRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDelayRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DelayRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DelayRequestValidationError{}
