// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/Jim3Things/CloudChamber/pkg/protos/inventory/external.proto

package inventory

import (
	fmt "fmt"
	common "github.com/Jim3Things/CloudChamber/pkg/protos/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type External struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *External) Reset()         { *m = External{} }
func (m *External) String() string { return proto.CompactTextString(m) }
func (*External) ProtoMessage()    {}
func (*External) Descriptor() ([]byte, []int) {
	return fileDescriptor_687eec8f588ec561, []int{0}
}

func (m *External) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_External.Unmarshal(m, b)
}
func (m *External) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_External.Marshal(b, m, deterministic)
}
func (m *External) XXX_Merge(src proto.Message) {
	xxx_messageInfo_External.Merge(m, src)
}
func (m *External) XXX_Size() int {
	return xxx_messageInfo_External.Size(m)
}
func (m *External) XXX_DiscardUnknown() {
	xxx_messageInfo_External.DiscardUnknown(m)
}

var xxx_messageInfo_External proto.InternalMessageInfo

type ExternalBlade struct {
	// specify which blade in the rack.
	// Note that full internal name for a blade is <rackname>-blade-<bladeId>
	Id                   int64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Capacity             *common.BladeCapacity `protobuf:"bytes,2,opt,name=capacity,proto3" json:"capacity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ExternalBlade) Reset()         { *m = ExternalBlade{} }
func (m *ExternalBlade) String() string { return proto.CompactTextString(m) }
func (*ExternalBlade) ProtoMessage()    {}
func (*ExternalBlade) Descriptor() ([]byte, []int) {
	return fileDescriptor_687eec8f588ec561, []int{0, 0}
}

func (m *ExternalBlade) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExternalBlade.Unmarshal(m, b)
}
func (m *ExternalBlade) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExternalBlade.Marshal(b, m, deterministic)
}
func (m *ExternalBlade) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExternalBlade.Merge(m, src)
}
func (m *ExternalBlade) XXX_Size() int {
	return xxx_messageInfo_ExternalBlade.Size(m)
}
func (m *ExternalBlade) XXX_DiscardUnknown() {
	xxx_messageInfo_ExternalBlade.DiscardUnknown(m)
}

var xxx_messageInfo_ExternalBlade proto.InternalMessageInfo

func (m *ExternalBlade) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ExternalBlade) GetCapacity() *common.BladeCapacity {
	if m != nil {
		return m.Capacity
	}
	return nil
}

// Power distribution unit.  Network accessible power controller
type ExternalPdu struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExternalPdu) Reset()         { *m = ExternalPdu{} }
func (m *ExternalPdu) String() string { return proto.CompactTextString(m) }
func (*ExternalPdu) ProtoMessage()    {}
func (*ExternalPdu) Descriptor() ([]byte, []int) {
	return fileDescriptor_687eec8f588ec561, []int{0, 1}
}

func (m *ExternalPdu) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExternalPdu.Unmarshal(m, b)
}
func (m *ExternalPdu) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExternalPdu.Marshal(b, m, deterministic)
}
func (m *ExternalPdu) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExternalPdu.Merge(m, src)
}
func (m *ExternalPdu) XXX_Size() int {
	return xxx_messageInfo_ExternalPdu.Size(m)
}
func (m *ExternalPdu) XXX_DiscardUnknown() {
	xxx_messageInfo_ExternalPdu.DiscardUnknown(m)
}

var xxx_messageInfo_ExternalPdu proto.InternalMessageInfo

// Rack-level network switch.
type ExternalTor struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExternalTor) Reset()         { *m = ExternalTor{} }
func (m *ExternalTor) String() string { return proto.CompactTextString(m) }
func (*ExternalTor) ProtoMessage()    {}
func (*ExternalTor) Descriptor() ([]byte, []int) {
	return fileDescriptor_687eec8f588ec561, []int{0, 2}
}

func (m *ExternalTor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExternalTor.Unmarshal(m, b)
}
func (m *ExternalTor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExternalTor.Marshal(b, m, deterministic)
}
func (m *ExternalTor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExternalTor.Merge(m, src)
}
func (m *ExternalTor) XXX_Size() int {
	return xxx_messageInfo_ExternalTor.Size(m)
}
func (m *ExternalTor) XXX_DiscardUnknown() {
	xxx_messageInfo_ExternalTor.DiscardUnknown(m)
}

var xxx_messageInfo_ExternalTor proto.InternalMessageInfo

// Management controller.  Provides direct ability halt or boot a specific
// blade.
type ExternalMc struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExternalMc) Reset()         { *m = ExternalMc{} }
func (m *ExternalMc) String() string { return proto.CompactTextString(m) }
func (*ExternalMc) ProtoMessage()    {}
func (*ExternalMc) Descriptor() ([]byte, []int) {
	return fileDescriptor_687eec8f588ec561, []int{0, 3}
}

func (m *ExternalMc) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExternalMc.Unmarshal(m, b)
}
func (m *ExternalMc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExternalMc.Marshal(b, m, deterministic)
}
func (m *ExternalMc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExternalMc.Merge(m, src)
}
func (m *ExternalMc) XXX_Size() int {
	return xxx_messageInfo_ExternalMc.Size(m)
}
func (m *ExternalMc) XXX_DiscardUnknown() {
	xxx_messageInfo_ExternalMc.DiscardUnknown(m)
}

var xxx_messageInfo_ExternalMc proto.InternalMessageInfo

type ExternalRack struct {
	Name                 string           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Pdu                  *ExternalPdu     `protobuf:"bytes,2,opt,name=pdu,proto3" json:"pdu,omitempty"`
	Tor                  *ExternalTor     `protobuf:"bytes,3,opt,name=tor,proto3" json:"tor,omitempty"`
	Mc                   *ExternalMc      `protobuf:"bytes,4,opt,name=mc,proto3" json:"mc,omitempty"`
	Blade                []*ExternalBlade `protobuf:"bytes,5,rep,name=blade,proto3" json:"blade,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ExternalRack) Reset()         { *m = ExternalRack{} }
func (m *ExternalRack) String() string { return proto.CompactTextString(m) }
func (*ExternalRack) ProtoMessage()    {}
func (*ExternalRack) Descriptor() ([]byte, []int) {
	return fileDescriptor_687eec8f588ec561, []int{0, 4}
}

func (m *ExternalRack) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExternalRack.Unmarshal(m, b)
}
func (m *ExternalRack) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExternalRack.Marshal(b, m, deterministic)
}
func (m *ExternalRack) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExternalRack.Merge(m, src)
}
func (m *ExternalRack) XXX_Size() int {
	return xxx_messageInfo_ExternalRack.Size(m)
}
func (m *ExternalRack) XXX_DiscardUnknown() {
	xxx_messageInfo_ExternalRack.DiscardUnknown(m)
}

var xxx_messageInfo_ExternalRack proto.InternalMessageInfo

func (m *ExternalRack) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ExternalRack) GetPdu() *ExternalPdu {
	if m != nil {
		return m.Pdu
	}
	return nil
}

func (m *ExternalRack) GetTor() *ExternalTor {
	if m != nil {
		return m.Tor
	}
	return nil
}

func (m *ExternalRack) GetMc() *ExternalMc {
	if m != nil {
		return m.Mc
	}
	return nil
}

func (m *ExternalRack) GetBlade() []*ExternalBlade {
	if m != nil {
		return m.Blade
	}
	return nil
}

// This is probably not needed at this point.
type ExternalZone struct {
	Racks                []*ExternalRack `protobuf:"bytes,1,rep,name=racks,proto3" json:"racks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ExternalZone) Reset()         { *m = ExternalZone{} }
func (m *ExternalZone) String() string { return proto.CompactTextString(m) }
func (*ExternalZone) ProtoMessage()    {}
func (*ExternalZone) Descriptor() ([]byte, []int) {
	return fileDescriptor_687eec8f588ec561, []int{0, 5}
}

func (m *ExternalZone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExternalZone.Unmarshal(m, b)
}
func (m *ExternalZone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExternalZone.Marshal(b, m, deterministic)
}
func (m *ExternalZone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExternalZone.Merge(m, src)
}
func (m *ExternalZone) XXX_Size() int {
	return xxx_messageInfo_ExternalZone.Size(m)
}
func (m *ExternalZone) XXX_DiscardUnknown() {
	xxx_messageInfo_ExternalZone.DiscardUnknown(m)
}

var xxx_messageInfo_ExternalZone proto.InternalMessageInfo

func (m *ExternalZone) GetRacks() []*ExternalRack {
	if m != nil {
		return m.Racks
	}
	return nil
}

func init() {
	proto.RegisterType((*External)(nil), "inventory.external")
	proto.RegisterType((*ExternalBlade)(nil), "inventory.external.blade")
	proto.RegisterType((*ExternalPdu)(nil), "inventory.external.pdu")
	proto.RegisterType((*ExternalTor)(nil), "inventory.external.tor")
	proto.RegisterType((*ExternalMc)(nil), "inventory.external.mc")
	proto.RegisterType((*ExternalRack)(nil), "inventory.external.rack")
	proto.RegisterType((*ExternalZone)(nil), "inventory.external.zone")
}

func init() {
	proto.RegisterFile("github.com/Jim3Things/CloudChamber/pkg/protos/inventory/external.proto", fileDescriptor_687eec8f588ec561)
}

var fileDescriptor_687eec8f588ec561 = []byte{
	// 311 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0x31, 0x4f, 0x33, 0x21,
	0x1c, 0xc6, 0x73, 0xdc, 0xdd, 0x9b, 0x96, 0x26, 0xef, 0xc0, 0xa0, 0xc8, 0xd4, 0x38, 0x98, 0xba,
	0x40, 0xd2, 0x26, 0x1a, 0x47, 0x6d, 0xe2, 0xa0, 0x1b, 0x71, 0x72, 0x31, 0x1c, 0x90, 0x96, 0xb4,
	0xc0, 0x85, 0x72, 0xc6, 0xfa, 0x0d, 0xfd, 0x34, 0x7e, 0x05, 0x03, 0xbd, 0xd6, 0xa5, 0x0e, 0x3a,
	0xfd, 0x2f, 0xf7, 0xff, 0x3d, 0xcf, 0xc3, 0x43, 0x80, 0xf7, 0x0b, 0x13, 0x97, 0x5d, 0x43, 0xa5,
	0xb7, 0xec, 0xc1, 0xd8, 0xd9, 0xd3, 0xd2, 0xb8, 0xc5, 0x86, 0xcd, 0xd7, 0xbe, 0x53, 0xf3, 0xa5,
	0xb0, 0x8d, 0x0e, 0xac, 0x5d, 0x2d, 0x58, 0x1b, 0x7c, 0xf4, 0x1b, 0x66, 0xdc, 0xab, 0x76, 0xd1,
	0x87, 0x2d, 0xd3, 0x6f, 0x51, 0x07, 0x27, 0xd6, 0x34, 0x6f, 0xd0, 0xf0, 0xb0, 0x21, 0xb7, 0xbf,
	0xb3, 0x94, 0xde, 0x5a, 0xef, 0xfa, 0xb1, 0x73, 0x3b, 0xff, 0x04, 0x70, 0xb0, 0x0f, 0x20, 0x8f,
	0xb0, 0x6e, 0xd6, 0x42, 0x69, 0xf4, 0x1f, 0x02, 0xa3, 0x70, 0x31, 0x2e, 0x26, 0x25, 0x07, 0x46,
	0xa1, 0x29, 0x1c, 0x48, 0xd1, 0x0a, 0x69, 0xe2, 0x16, 0x83, 0x71, 0x31, 0x19, 0x4d, 0x4f, 0x68,
	0x6f, 0x93, 0x05, 0x2f, 0xfb, 0x2d, 0x3f, 0x70, 0xa4, 0x86, 0x65, 0xab, 0xba, 0x34, 0xa2, 0x0f,
	0xa4, 0x82, 0xc0, 0x4a, 0xf2, 0x51, 0xc0, 0x2a, 0x08, 0xb9, 0x42, 0x08, 0x56, 0x4e, 0x58, 0x9d,
	0x23, 0x86, 0x3c, 0x7f, 0xa3, 0xcb, 0x2c, 0xe8, 0xfd, 0x4f, 0xe9, 0xa1, 0x26, 0xfd, 0xbe, 0x00,
	0xd5, 0xf1, 0xc4, 0x24, 0x34, 0xfa, 0x80, 0xcb, 0x9f, 0xd1, 0xe8, 0x03, 0x4f, 0x0c, 0xba, 0x48,
	0xc1, 0xb8, 0xea, 0x0f, 0x7d, 0x84, 0xb4, 0x92, 0x03, 0x2b, 0x11, 0xeb, 0xbb, 0xe3, 0x7a, 0x5c,
	0x4e, 0x46, 0xd3, 0xb3, 0x63, 0x68, 0x06, 0xf8, 0x8e, 0x23, 0x57, 0xb0, 0x7a, 0xf7, 0x4e, 0x23,
	0x0a, 0xeb, 0x54, 0x69, 0x83, 0x8b, 0x2c, 0xc4, 0xc7, 0x84, 0x09, 0xe0, 0x3b, 0xec, 0xee, 0xe6,
	0xf9, 0xfa, 0x8f, 0x2f, 0xa1, 0xf9, 0x97, 0xff, 0xcc, 0xbe, 0x02, 0x00, 0x00, 0xff, 0xff, 0xcc,
	0x9a, 0x3d, 0xe7, 0x4b, 0x02, 0x00, 0x00,
}
