// Code generated by protoc-gen-go. DO NOT EDIT.
// source: inventory/external.proto

package inventory

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type External struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *External) Reset()         { *m = External{} }
func (m *External) String() string { return proto.CompactTextString(m) }
func (*External) ProtoMessage()    {}
func (*External) Descriptor() ([]byte, []int) {
	return fileDescriptor_1435d45dd7b5863a, []int{0}
}

func (m *External) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_External.Unmarshal(m, b)
}
func (m *External) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_External.Marshal(b, m, deterministic)
}
func (m *External) XXX_Merge(src proto.Message) {
	xxx_messageInfo_External.Merge(m, src)
}
func (m *External) XXX_Size() int {
	return xxx_messageInfo_External.Size(m)
}
func (m *External) XXX_DiscardUnknown() {
	xxx_messageInfo_External.DiscardUnknown(m)
}

var xxx_messageInfo_External proto.InternalMessageInfo

// Describe the capabilities of a physical blade
// TODO: Should architecture be a core attribute of a blade?
// TODO: Do we need anything about host system software, or is this purely physical attributes?
type ExternalBlade struct {
	// specify which blade in the rack.
	// Note that full internal name for a blade is <rackname>-blade-<bladeId>
	Id                   int64                   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Cores                int64                   `protobuf:"varint,2,opt,name=cores,proto3" json:"cores,omitempty"`
	MemoryInMb           int64                   `protobuf:"varint,3,opt,name=memory_in_mb,json=memoryInMb,proto3" json:"memory_in_mb,omitempty"`
	DiskInGb             int64                   `protobuf:"varint,4,opt,name=disk_in_gb,json=diskInGb,proto3" json:"disk_in_gb,omitempty"`
	NetworkBandwidth     int64                   `protobuf:"varint,5,opt,name=network_bandwidth,json=networkBandwidth,proto3" json:"network_bandwidth,omitempty"`
	Features             []*ExternalBladeFeature `protobuf:"bytes,6,rep,name=features,proto3" json:"features,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ExternalBlade) Reset()         { *m = ExternalBlade{} }
func (m *ExternalBlade) String() string { return proto.CompactTextString(m) }
func (*ExternalBlade) ProtoMessage()    {}
func (*ExternalBlade) Descriptor() ([]byte, []int) {
	return fileDescriptor_1435d45dd7b5863a, []int{0, 0}
}

func (m *ExternalBlade) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExternalBlade.Unmarshal(m, b)
}
func (m *ExternalBlade) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExternalBlade.Marshal(b, m, deterministic)
}
func (m *ExternalBlade) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExternalBlade.Merge(m, src)
}
func (m *ExternalBlade) XXX_Size() int {
	return xxx_messageInfo_ExternalBlade.Size(m)
}
func (m *ExternalBlade) XXX_DiscardUnknown() {
	xxx_messageInfo_ExternalBlade.DiscardUnknown(m)
}

var xxx_messageInfo_ExternalBlade proto.InternalMessageInfo

func (m *ExternalBlade) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ExternalBlade) GetCores() int64 {
	if m != nil {
		return m.Cores
	}
	return 0
}

func (m *ExternalBlade) GetMemoryInMb() int64 {
	if m != nil {
		return m.MemoryInMb
	}
	return 0
}

func (m *ExternalBlade) GetDiskInGb() int64 {
	if m != nil {
		return m.DiskInGb
	}
	return 0
}

func (m *ExternalBlade) GetNetworkBandwidth() int64 {
	if m != nil {
		return m.NetworkBandwidth
	}
	return 0
}

func (m *ExternalBlade) GetFeatures() []*ExternalBladeFeature {
	if m != nil {
		return m.Features
	}
	return nil
}

// Used to define an extended feature of the blade, such as GPU
type ExternalBladeFeature struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Amount               int64    `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExternalBladeFeature) Reset()         { *m = ExternalBladeFeature{} }
func (m *ExternalBladeFeature) String() string { return proto.CompactTextString(m) }
func (*ExternalBladeFeature) ProtoMessage()    {}
func (*ExternalBladeFeature) Descriptor() ([]byte, []int) {
	return fileDescriptor_1435d45dd7b5863a, []int{0, 0, 0}
}

func (m *ExternalBladeFeature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExternalBladeFeature.Unmarshal(m, b)
}
func (m *ExternalBladeFeature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExternalBladeFeature.Marshal(b, m, deterministic)
}
func (m *ExternalBladeFeature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExternalBladeFeature.Merge(m, src)
}
func (m *ExternalBladeFeature) XXX_Size() int {
	return xxx_messageInfo_ExternalBladeFeature.Size(m)
}
func (m *ExternalBladeFeature) XXX_DiscardUnknown() {
	xxx_messageInfo_ExternalBladeFeature.DiscardUnknown(m)
}

var xxx_messageInfo_ExternalBladeFeature proto.InternalMessageInfo

func (m *ExternalBladeFeature) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ExternalBladeFeature) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

// Power distribution unit.  Network accessible power controller
type ExternalPdu struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExternalPdu) Reset()         { *m = ExternalPdu{} }
func (m *ExternalPdu) String() string { return proto.CompactTextString(m) }
func (*ExternalPdu) ProtoMessage()    {}
func (*ExternalPdu) Descriptor() ([]byte, []int) {
	return fileDescriptor_1435d45dd7b5863a, []int{0, 1}
}

func (m *ExternalPdu) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExternalPdu.Unmarshal(m, b)
}
func (m *ExternalPdu) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExternalPdu.Marshal(b, m, deterministic)
}
func (m *ExternalPdu) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExternalPdu.Merge(m, src)
}
func (m *ExternalPdu) XXX_Size() int {
	return xxx_messageInfo_ExternalPdu.Size(m)
}
func (m *ExternalPdu) XXX_DiscardUnknown() {
	xxx_messageInfo_ExternalPdu.DiscardUnknown(m)
}

var xxx_messageInfo_ExternalPdu proto.InternalMessageInfo

// Rack-level network switch.
type ExternalTor struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExternalTor) Reset()         { *m = ExternalTor{} }
func (m *ExternalTor) String() string { return proto.CompactTextString(m) }
func (*ExternalTor) ProtoMessage()    {}
func (*ExternalTor) Descriptor() ([]byte, []int) {
	return fileDescriptor_1435d45dd7b5863a, []int{0, 2}
}

func (m *ExternalTor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExternalTor.Unmarshal(m, b)
}
func (m *ExternalTor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExternalTor.Marshal(b, m, deterministic)
}
func (m *ExternalTor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExternalTor.Merge(m, src)
}
func (m *ExternalTor) XXX_Size() int {
	return xxx_messageInfo_ExternalTor.Size(m)
}
func (m *ExternalTor) XXX_DiscardUnknown() {
	xxx_messageInfo_ExternalTor.DiscardUnknown(m)
}

var xxx_messageInfo_ExternalTor proto.InternalMessageInfo

// Management controller.  Provides direct ability halt or boot a specific
// blade.
type ExternalMc struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExternalMc) Reset()         { *m = ExternalMc{} }
func (m *ExternalMc) String() string { return proto.CompactTextString(m) }
func (*ExternalMc) ProtoMessage()    {}
func (*ExternalMc) Descriptor() ([]byte, []int) {
	return fileDescriptor_1435d45dd7b5863a, []int{0, 3}
}

func (m *ExternalMc) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExternalMc.Unmarshal(m, b)
}
func (m *ExternalMc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExternalMc.Marshal(b, m, deterministic)
}
func (m *ExternalMc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExternalMc.Merge(m, src)
}
func (m *ExternalMc) XXX_Size() int {
	return xxx_messageInfo_ExternalMc.Size(m)
}
func (m *ExternalMc) XXX_DiscardUnknown() {
	xxx_messageInfo_ExternalMc.DiscardUnknown(m)
}

var xxx_messageInfo_ExternalMc proto.InternalMessageInfo

type ExternalRack struct {
	Name                 string           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Pdu                  *ExternalPdu     `protobuf:"bytes,2,opt,name=pdu,proto3" json:"pdu,omitempty"`
	Tor                  *ExternalTor     `protobuf:"bytes,3,opt,name=tor,proto3" json:"tor,omitempty"`
	Mc                   *ExternalMc      `protobuf:"bytes,4,opt,name=mc,proto3" json:"mc,omitempty"`
	Blade                []*ExternalBlade `protobuf:"bytes,5,rep,name=blade,proto3" json:"blade,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ExternalRack) Reset()         { *m = ExternalRack{} }
func (m *ExternalRack) String() string { return proto.CompactTextString(m) }
func (*ExternalRack) ProtoMessage()    {}
func (*ExternalRack) Descriptor() ([]byte, []int) {
	return fileDescriptor_1435d45dd7b5863a, []int{0, 4}
}

func (m *ExternalRack) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExternalRack.Unmarshal(m, b)
}
func (m *ExternalRack) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExternalRack.Marshal(b, m, deterministic)
}
func (m *ExternalRack) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExternalRack.Merge(m, src)
}
func (m *ExternalRack) XXX_Size() int {
	return xxx_messageInfo_ExternalRack.Size(m)
}
func (m *ExternalRack) XXX_DiscardUnknown() {
	xxx_messageInfo_ExternalRack.DiscardUnknown(m)
}

var xxx_messageInfo_ExternalRack proto.InternalMessageInfo

func (m *ExternalRack) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ExternalRack) GetPdu() *ExternalPdu {
	if m != nil {
		return m.Pdu
	}
	return nil
}

func (m *ExternalRack) GetTor() *ExternalTor {
	if m != nil {
		return m.Tor
	}
	return nil
}

func (m *ExternalRack) GetMc() *ExternalMc {
	if m != nil {
		return m.Mc
	}
	return nil
}

func (m *ExternalRack) GetBlade() []*ExternalBlade {
	if m != nil {
		return m.Blade
	}
	return nil
}

// This is probably not needed at this point.
type ExternalZone struct {
	Racks                []*ExternalRack `protobuf:"bytes,1,rep,name=racks,proto3" json:"racks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ExternalZone) Reset()         { *m = ExternalZone{} }
func (m *ExternalZone) String() string { return proto.CompactTextString(m) }
func (*ExternalZone) ProtoMessage()    {}
func (*ExternalZone) Descriptor() ([]byte, []int) {
	return fileDescriptor_1435d45dd7b5863a, []int{0, 5}
}

func (m *ExternalZone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExternalZone.Unmarshal(m, b)
}
func (m *ExternalZone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExternalZone.Marshal(b, m, deterministic)
}
func (m *ExternalZone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExternalZone.Merge(m, src)
}
func (m *ExternalZone) XXX_Size() int {
	return xxx_messageInfo_ExternalZone.Size(m)
}
func (m *ExternalZone) XXX_DiscardUnknown() {
	xxx_messageInfo_ExternalZone.DiscardUnknown(m)
}

var xxx_messageInfo_ExternalZone proto.InternalMessageInfo

func (m *ExternalZone) GetRacks() []*ExternalRack {
	if m != nil {
		return m.Racks
	}
	return nil
}

func init() {
	proto.RegisterType((*External)(nil), "inventory.external")
	proto.RegisterType((*ExternalBlade)(nil), "inventory.external.blade")
	proto.RegisterType((*ExternalBladeFeature)(nil), "inventory.external.blade.feature")
	proto.RegisterType((*ExternalPdu)(nil), "inventory.external.pdu")
	proto.RegisterType((*ExternalTor)(nil), "inventory.external.tor")
	proto.RegisterType((*ExternalMc)(nil), "inventory.external.mc")
	proto.RegisterType((*ExternalRack)(nil), "inventory.external.rack")
	proto.RegisterType((*ExternalZone)(nil), "inventory.external.zone")
}

func init() { proto.RegisterFile("inventory/external.proto", fileDescriptor_1435d45dd7b5863a) }

var fileDescriptor_1435d45dd7b5863a = []byte{
	// 351 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x4f, 0x4e, 0xf3, 0x30,
	0x10, 0xc5, 0x95, 0x7f, 0xfd, 0xda, 0xe9, 0x27, 0x04, 0x16, 0x2a, 0x26, 0x62, 0x51, 0x58, 0xa0,
	0x22, 0xa4, 0x54, 0x2a, 0x82, 0x1d, 0x1b, 0x36, 0xa8, 0x0b, 0x36, 0xbe, 0x40, 0x15, 0xc7, 0x06,
	0xa2, 0xd6, 0x76, 0xe5, 0x3a, 0x94, 0x72, 0x0a, 0x2e, 0xc3, 0x21, 0xb8, 0x15, 0xf2, 0x24, 0xcd,
	0x2a, 0x5d, 0xc5, 0x9e, 0xf7, 0x9b, 0xc9, 0xbc, 0x97, 0x00, 0x2d, 0xf5, 0x87, 0xd4, 0xce, 0xd8,
	0xdd, 0x54, 0x7e, 0x3a, 0x69, 0x75, 0xbe, 0xca, 0xd6, 0xd6, 0x38, 0x43, 0x06, 0xad, 0x72, 0xf5,
	0x13, 0x43, 0x7f, 0xaf, 0xa6, 0xdf, 0x21, 0x24, 0x7c, 0x95, 0x0b, 0x49, 0x8e, 0x20, 0x2c, 0x05,
	0x0d, 0xc6, 0xc1, 0x24, 0x62, 0x61, 0x29, 0xc8, 0x29, 0x24, 0x85, 0xb1, 0x72, 0x43, 0x43, 0x2c,
	0xd5, 0x17, 0x32, 0x86, 0xff, 0x4a, 0x2a, 0x63, 0x77, 0x8b, 0x52, 0x2f, 0x14, 0xa7, 0x11, 0x8a,
	0x50, 0xd7, 0xe6, 0xfa, 0x85, 0x93, 0x0b, 0x00, 0x51, 0x6e, 0x96, 0x5e, 0x7f, 0xe3, 0x34, 0x46,
	0xbd, 0xef, 0x2b, 0x73, 0xfd, 0xcc, 0xc9, 0x2d, 0x9c, 0x68, 0xe9, 0xb6, 0xc6, 0x2e, 0x17, 0x3c,
	0xd7, 0x62, 0x5b, 0x0a, 0xf7, 0x4e, 0x13, 0x84, 0x8e, 0x1b, 0xe1, 0x69, 0x5f, 0x27, 0x8f, 0xd0,
	0x7f, 0x95, 0xb9, 0xab, 0xfc, 0x16, 0xbd, 0x71, 0x34, 0x19, 0xce, 0x2e, 0xb3, 0xd6, 0x47, 0xd6,
	0x3a, 0xc4, 0xfd, 0xb3, 0x86, 0x64, 0x6d, 0x4b, 0x7a, 0x0f, 0xff, 0x9a, 0x33, 0x21, 0x10, 0xeb,
	0x5c, 0x49, 0xb4, 0x37, 0x60, 0x78, 0x26, 0x23, 0xe8, 0xe5, 0xca, 0x54, 0xda, 0x35, 0x0e, 0x9b,
	0x5b, 0x9a, 0x40, 0xb4, 0x16, 0x95, 0x7f, 0x38, 0x63, 0xd3, 0x18, 0x42, 0x55, 0xa4, 0xbf, 0x01,
	0xc4, 0x36, 0x2f, 0x96, 0x9d, 0x83, 0x6e, 0xb0, 0x01, 0xa7, 0x0c, 0x67, 0x67, 0x5d, 0x1b, 0xae,
	0x45, 0xc5, 0x3c, 0xe3, 0x51, 0x67, 0x2c, 0xa6, 0x76, 0x00, 0x75, 0xc6, 0x32, 0xcf, 0x90, 0x6b,
	0xff, 0x62, 0xcc, 0x6f, 0x38, 0x1b, 0x75, 0x91, 0xaa, 0x60, 0xa1, 0x2a, 0xc8, 0xb4, 0xf9, 0x80,
	0x34, 0xc1, 0x84, 0xce, 0x0f, 0x26, 0xc4, 0x6a, 0x2e, 0x7d, 0x80, 0xf8, 0xcb, 0x68, 0x49, 0x32,
	0x48, 0xbc, 0xa5, 0x0d, 0x0d, 0xb0, 0x91, 0x76, 0x35, 0x7a, 0x80, 0xd5, 0x18, 0xef, 0xe1, 0x9f,
	0x74, 0xf7, 0x17, 0x00, 0x00, 0xff, 0xff, 0x73, 0xc8, 0x9c, 0x0b, 0x65, 0x02, 0x00, 0x00,
}
