// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/Jim3Things/CloudChamber/pkg/protos/inventory/internal.proto

package inventory

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Internal struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Internal) Reset()         { *m = Internal{} }
func (m *Internal) String() string { return proto.CompactTextString(m) }
func (*Internal) ProtoMessage()    {}
func (*Internal) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b58c832b17aed9b, []int{0}
}

func (m *Internal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Internal.Unmarshal(m, b)
}
func (m *Internal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Internal.Marshal(b, m, deterministic)
}
func (m *Internal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Internal.Merge(m, src)
}
func (m *Internal) XXX_Size() int {
	return xxx_messageInfo_Internal.Size(m)
}
func (m *Internal) XXX_DiscardUnknown() {
	xxx_messageInfo_Internal.DiscardUnknown(m)
}

var xxx_messageInfo_Internal proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Internal)(nil), "inventory.internal")
}

func init() {
	proto.RegisterFile("github.com/Jim3Things/CloudChamber/pkg/protos/inventory/internal.proto", fileDescriptor_2b58c832b17aed9b)
}

var fileDescriptor_2b58c832b17aed9b = []byte{
	// 114 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x72, 0x4b, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0xf7, 0xca, 0xcc, 0x35, 0x0e, 0xc9, 0xc8, 0xcc, 0x4b,
	0x2f, 0xd6, 0x77, 0xce, 0xc9, 0x2f, 0x4d, 0x71, 0xce, 0x48, 0xcc, 0x4d, 0x4a, 0x2d, 0xd2, 0x2f,
	0xc8, 0x4e, 0xd7, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0x2f, 0xd6, 0xcf, 0xcc, 0x2b, 0x4b, 0xcd, 0x2b,
	0xc9, 0x2f, 0xaa, 0xd4, 0xcf, 0xcc, 0x2b, 0x49, 0x2d, 0xca, 0x4b, 0xcc, 0xd1, 0x03, 0xcb, 0x08,
	0x71, 0xc2, 0x65, 0x94, 0xb8, 0xb8, 0x38, 0x60, 0x92, 0x4e, 0x96, 0x51, 0xe6, 0x64, 0x5a, 0x90,
	0xc4, 0x06, 0x16, 0x31, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xe9, 0xcd, 0x77, 0xd1, 0xa2, 0x00,
	0x00, 0x00,
}
