// Code generated by protoc-gen-go. DO NOT EDIT.
// source: workload/actual.proto

package workload

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Actual struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Actual) Reset()         { *m = Actual{} }
func (m *Actual) String() string { return proto.CompactTextString(m) }
func (*Actual) ProtoMessage()    {}
func (*Actual) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2758c4613a64f92, []int{0}
}

func (m *Actual) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Actual.Unmarshal(m, b)
}
func (m *Actual) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Actual.Marshal(b, m, deterministic)
}
func (m *Actual) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Actual.Merge(m, src)
}
func (m *Actual) XXX_Size() int {
	return xxx_messageInfo_Actual.Size(m)
}
func (m *Actual) XXX_DiscardUnknown() {
	xxx_messageInfo_Actual.DiscardUnknown(m)
}

var xxx_messageInfo_Actual proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Actual)(nil), "workload.actual")
}

func init() { proto.RegisterFile("workload/actual.proto", fileDescriptor_a2758c4613a64f92) }

var fileDescriptor_a2758c4613a64f92 = []byte{
	// 62 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2d, 0xcf, 0x2f, 0xca,
	0xce, 0xc9, 0x4f, 0x4c, 0xd1, 0x4f, 0x4c, 0x2e, 0x29, 0x4d, 0xcc, 0xd1, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0xe2, 0x80, 0x09, 0x2b, 0x71, 0x70, 0xb1, 0x41, 0x64, 0x92, 0xd8, 0xc0, 0x52, 0xc6,
	0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6b, 0xf0, 0x96, 0xcd, 0x33, 0x00, 0x00, 0x00,
}
