// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/Jim3Things/CloudChamber/pkg/protos/monitor/monitor.proto

package monitor

import (
	context "context"
	fmt "fmt"
	common "github.com/Jim3Things/CloudChamber/pkg/protos/common"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ActualHealth int32

const (
	Actual_Invalid     ActualHealth = 0
	Actual_Unavailable ActualHealth = 1
	Actual_Draining    ActualHealth = 2
	Actual_Healthy     ActualHealth = 3
	Actual_Removing    ActualHealth = 4
)

var ActualHealth_name = map[int32]string{
	0: "Invalid",
	1: "Unavailable",
	2: "Draining",
	3: "Healthy",
	4: "Removing",
}

var ActualHealth_value = map[string]int32{
	"Invalid":     0,
	"Unavailable": 1,
	"Draining":    2,
	"Healthy":     3,
	"Removing":    4,
}

func (x ActualHealth) String() string {
	return proto.EnumName(ActualHealth_name, int32(x))
}

func (ActualHealth) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_318189739c1c4c20, []int{0, 0}
}

type DesiredHealth int32

const (
	Desired_Invalid  DesiredHealth = 0
	Desired_Draining DesiredHealth = 1
	Desired_Stopped  DesiredHealth = 2
	Desired_Healthy  DesiredHealth = 3
	Desired_Removed  DesiredHealth = 4
)

var DesiredHealth_name = map[int32]string{
	0: "Invalid",
	1: "Draining",
	2: "Stopped",
	3: "Healthy",
	4: "Removed",
}

var DesiredHealth_value = map[string]int32{
	"Invalid":  0,
	"Draining": 1,
	"Stopped":  2,
	"Healthy":  3,
	"Removed":  4,
}

func (x DesiredHealth) String() string {
	return proto.EnumName(DesiredHealth_name, int32(x))
}

func (DesiredHealth) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_318189739c1c4c20, []int{1, 0}
}

// NOTE: There is an aspect of this structure that I'm unhappy with - I'd like
//       the message structure to be sure that invalid combinations cannot be
//       created.  In other words, it is structurally impossible to create a
//       message that has an invalid combination of items.
//
//       This does not do that.  For example, capacity does not make sense if
//       the health is not 'Healthy'.  But it can be specified.
//
//       I considered extensive use of oneof to limit the options, but that
//       looked even worse.  Open to suggestions.
type Actual struct {
	Items                []*ActualItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Actual) Reset()         { *m = Actual{} }
func (m *Actual) String() string { return proto.CompactTextString(m) }
func (*Actual) ProtoMessage()    {}
func (*Actual) Descriptor() ([]byte, []int) {
	return fileDescriptor_318189739c1c4c20, []int{0}
}

func (m *Actual) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Actual.Unmarshal(m, b)
}
func (m *Actual) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Actual.Marshal(b, m, deterministic)
}
func (m *Actual) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Actual.Merge(m, src)
}
func (m *Actual) XXX_Size() int {
	return xxx_messageInfo_Actual.Size(m)
}
func (m *Actual) XXX_DiscardUnknown() {
	xxx_messageInfo_Actual.DiscardUnknown(m)
}

var xxx_messageInfo_Actual proto.InternalMessageInfo

func (m *Actual) GetItems() []*ActualItem {
	if m != nil {
		return m.Items
	}
	return nil
}

type ActualBladeDetails struct {
	// specify which blade in the rack.
	// Note that full internal name for a blade is <rackname>-blade-<bladeId>
	Id                   int64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Present              *common.BladeCapacity `protobuf:"bytes,2,opt,name=present,proto3" json:"present,omitempty"`
	Used                 *common.BladeCapacity `protobuf:"bytes,3,opt,name=used,proto3" json:"used,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ActualBladeDetails) Reset()         { *m = ActualBladeDetails{} }
func (m *ActualBladeDetails) String() string { return proto.CompactTextString(m) }
func (*ActualBladeDetails) ProtoMessage()    {}
func (*ActualBladeDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_318189739c1c4c20, []int{0, 0}
}

func (m *ActualBladeDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActualBladeDetails.Unmarshal(m, b)
}
func (m *ActualBladeDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActualBladeDetails.Marshal(b, m, deterministic)
}
func (m *ActualBladeDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActualBladeDetails.Merge(m, src)
}
func (m *ActualBladeDetails) XXX_Size() int {
	return xxx_messageInfo_ActualBladeDetails.Size(m)
}
func (m *ActualBladeDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_ActualBladeDetails.DiscardUnknown(m)
}

var xxx_messageInfo_ActualBladeDetails proto.InternalMessageInfo

func (m *ActualBladeDetails) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ActualBladeDetails) GetPresent() *common.BladeCapacity {
	if m != nil {
		return m.Present
	}
	return nil
}

func (m *ActualBladeDetails) GetUsed() *common.BladeCapacity {
	if m != nil {
		return m.Used
	}
	return nil
}

type ActualPduDetails struct {
	Cables               map[int64]bool `protobuf:"bytes,1,rep,name=cables,proto3" json:"cables,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ActualPduDetails) Reset()         { *m = ActualPduDetails{} }
func (m *ActualPduDetails) String() string { return proto.CompactTextString(m) }
func (*ActualPduDetails) ProtoMessage()    {}
func (*ActualPduDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_318189739c1c4c20, []int{0, 1}
}

func (m *ActualPduDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActualPduDetails.Unmarshal(m, b)
}
func (m *ActualPduDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActualPduDetails.Marshal(b, m, deterministic)
}
func (m *ActualPduDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActualPduDetails.Merge(m, src)
}
func (m *ActualPduDetails) XXX_Size() int {
	return xxx_messageInfo_ActualPduDetails.Size(m)
}
func (m *ActualPduDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_ActualPduDetails.DiscardUnknown(m)
}

var xxx_messageInfo_ActualPduDetails proto.InternalMessageInfo

func (m *ActualPduDetails) GetCables() map[int64]bool {
	if m != nil {
		return m.Cables
	}
	return nil
}

type ActualTorDetails struct {
	Cables               map[int64]bool `protobuf:"bytes,1,rep,name=cables,proto3" json:"cables,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ActualTorDetails) Reset()         { *m = ActualTorDetails{} }
func (m *ActualTorDetails) String() string { return proto.CompactTextString(m) }
func (*ActualTorDetails) ProtoMessage()    {}
func (*ActualTorDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_318189739c1c4c20, []int{0, 2}
}

func (m *ActualTorDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActualTorDetails.Unmarshal(m, b)
}
func (m *ActualTorDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActualTorDetails.Marshal(b, m, deterministic)
}
func (m *ActualTorDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActualTorDetails.Merge(m, src)
}
func (m *ActualTorDetails) XXX_Size() int {
	return xxx_messageInfo_ActualTorDetails.Size(m)
}
func (m *ActualTorDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_ActualTorDetails.DiscardUnknown(m)
}

var xxx_messageInfo_ActualTorDetails proto.InternalMessageInfo

func (m *ActualTorDetails) GetCables() map[int64]bool {
	if m != nil {
		return m.Cables
	}
	return nil
}

type ActualItem struct {
	RackName  string            `protobuf:"bytes,1,opt,name=rack_name,json=rackName,proto3" json:"rack_name,omitempty"`
	Health    ActualHealth      `protobuf:"varint,2,opt,name=health,proto3,enum=monitor.ActualHealth" json:"health,omitempty"`
	LastStart *common.Timestamp `protobuf:"bytes,3,opt,name=last_start,json=lastStart,proto3" json:"last_start,omitempty"`
	// Types that are valid to be assigned to Details:
	//	*ActualItem_Blade
	//	*ActualItem_Pdu
	//	*ActualItem_Tor
	Details              isActualItem_Details `protobuf_oneof:"details"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ActualItem) Reset()         { *m = ActualItem{} }
func (m *ActualItem) String() string { return proto.CompactTextString(m) }
func (*ActualItem) ProtoMessage()    {}
func (*ActualItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_318189739c1c4c20, []int{0, 3}
}

func (m *ActualItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActualItem.Unmarshal(m, b)
}
func (m *ActualItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActualItem.Marshal(b, m, deterministic)
}
func (m *ActualItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActualItem.Merge(m, src)
}
func (m *ActualItem) XXX_Size() int {
	return xxx_messageInfo_ActualItem.Size(m)
}
func (m *ActualItem) XXX_DiscardUnknown() {
	xxx_messageInfo_ActualItem.DiscardUnknown(m)
}

var xxx_messageInfo_ActualItem proto.InternalMessageInfo

func (m *ActualItem) GetRackName() string {
	if m != nil {
		return m.RackName
	}
	return ""
}

func (m *ActualItem) GetHealth() ActualHealth {
	if m != nil {
		return m.Health
	}
	return Actual_Invalid
}

func (m *ActualItem) GetLastStart() *common.Timestamp {
	if m != nil {
		return m.LastStart
	}
	return nil
}

type isActualItem_Details interface {
	isActualItem_Details()
}

type ActualItem_Blade struct {
	Blade *ActualBladeDetails `protobuf:"bytes,4,opt,name=blade,proto3,oneof"`
}

type ActualItem_Pdu struct {
	Pdu *ActualPduDetails `protobuf:"bytes,5,opt,name=pdu,proto3,oneof"`
}

type ActualItem_Tor struct {
	Tor *ActualTorDetails `protobuf:"bytes,6,opt,name=tor,proto3,oneof"`
}

func (*ActualItem_Blade) isActualItem_Details() {}

func (*ActualItem_Pdu) isActualItem_Details() {}

func (*ActualItem_Tor) isActualItem_Details() {}

func (m *ActualItem) GetDetails() isActualItem_Details {
	if m != nil {
		return m.Details
	}
	return nil
}

func (m *ActualItem) GetBlade() *ActualBladeDetails {
	if x, ok := m.GetDetails().(*ActualItem_Blade); ok {
		return x.Blade
	}
	return nil
}

func (m *ActualItem) GetPdu() *ActualPduDetails {
	if x, ok := m.GetDetails().(*ActualItem_Pdu); ok {
		return x.Pdu
	}
	return nil
}

func (m *ActualItem) GetTor() *ActualTorDetails {
	if x, ok := m.GetDetails().(*ActualItem_Tor); ok {
		return x.Tor
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ActualItem) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ActualItem_Blade)(nil),
		(*ActualItem_Pdu)(nil),
		(*ActualItem_Tor)(nil),
	}
}

// This message describes a command from the monitor to the inventory.  These
// take the form of desired states for specific items.  Any item not mentioned
// has no actions to take.
//
// NOTE: This message has an even more obvious issue with legal-but-invalid
//       structures: teh last start time is not valid for several of the
//       health states.
type Desired struct {
	Items                []*DesiredItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Desired) Reset()         { *m = Desired{} }
func (m *Desired) String() string { return proto.CompactTextString(m) }
func (*Desired) ProtoMessage()    {}
func (*Desired) Descriptor() ([]byte, []int) {
	return fileDescriptor_318189739c1c4c20, []int{1}
}

func (m *Desired) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Desired.Unmarshal(m, b)
}
func (m *Desired) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Desired.Marshal(b, m, deterministic)
}
func (m *Desired) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Desired.Merge(m, src)
}
func (m *Desired) XXX_Size() int {
	return xxx_messageInfo_Desired.Size(m)
}
func (m *Desired) XXX_DiscardUnknown() {
	xxx_messageInfo_Desired.DiscardUnknown(m)
}

var xxx_messageInfo_Desired proto.InternalMessageInfo

func (m *Desired) GetItems() []*DesiredItem {
	if m != nil {
		return m.Items
	}
	return nil
}

type DesiredBladeDetails struct {
	// specify which blade in the rack.
	// Note that full internal name for a blade is <rackname>-blade-<bladeId>
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DesiredBladeDetails) Reset()         { *m = DesiredBladeDetails{} }
func (m *DesiredBladeDetails) String() string { return proto.CompactTextString(m) }
func (*DesiredBladeDetails) ProtoMessage()    {}
func (*DesiredBladeDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_318189739c1c4c20, []int{1, 0}
}

func (m *DesiredBladeDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DesiredBladeDetails.Unmarshal(m, b)
}
func (m *DesiredBladeDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DesiredBladeDetails.Marshal(b, m, deterministic)
}
func (m *DesiredBladeDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DesiredBladeDetails.Merge(m, src)
}
func (m *DesiredBladeDetails) XXX_Size() int {
	return xxx_messageInfo_DesiredBladeDetails.Size(m)
}
func (m *DesiredBladeDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_DesiredBladeDetails.DiscardUnknown(m)
}

var xxx_messageInfo_DesiredBladeDetails proto.InternalMessageInfo

func (m *DesiredBladeDetails) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DesiredPduDetails struct {
	Cables               map[int64]bool `protobuf:"bytes,1,rep,name=cables,proto3" json:"cables,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *DesiredPduDetails) Reset()         { *m = DesiredPduDetails{} }
func (m *DesiredPduDetails) String() string { return proto.CompactTextString(m) }
func (*DesiredPduDetails) ProtoMessage()    {}
func (*DesiredPduDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_318189739c1c4c20, []int{1, 1}
}

func (m *DesiredPduDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DesiredPduDetails.Unmarshal(m, b)
}
func (m *DesiredPduDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DesiredPduDetails.Marshal(b, m, deterministic)
}
func (m *DesiredPduDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DesiredPduDetails.Merge(m, src)
}
func (m *DesiredPduDetails) XXX_Size() int {
	return xxx_messageInfo_DesiredPduDetails.Size(m)
}
func (m *DesiredPduDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_DesiredPduDetails.DiscardUnknown(m)
}

var xxx_messageInfo_DesiredPduDetails proto.InternalMessageInfo

func (m *DesiredPduDetails) GetCables() map[int64]bool {
	if m != nil {
		return m.Cables
	}
	return nil
}

type DesiredTorDetails struct {
	Cables               map[int64]bool `protobuf:"bytes,1,rep,name=cables,proto3" json:"cables,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *DesiredTorDetails) Reset()         { *m = DesiredTorDetails{} }
func (m *DesiredTorDetails) String() string { return proto.CompactTextString(m) }
func (*DesiredTorDetails) ProtoMessage()    {}
func (*DesiredTorDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_318189739c1c4c20, []int{1, 2}
}

func (m *DesiredTorDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DesiredTorDetails.Unmarshal(m, b)
}
func (m *DesiredTorDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DesiredTorDetails.Marshal(b, m, deterministic)
}
func (m *DesiredTorDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DesiredTorDetails.Merge(m, src)
}
func (m *DesiredTorDetails) XXX_Size() int {
	return xxx_messageInfo_DesiredTorDetails.Size(m)
}
func (m *DesiredTorDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_DesiredTorDetails.DiscardUnknown(m)
}

var xxx_messageInfo_DesiredTorDetails proto.InternalMessageInfo

func (m *DesiredTorDetails) GetCables() map[int64]bool {
	if m != nil {
		return m.Cables
	}
	return nil
}

type DesiredItem struct {
	RackName  string            `protobuf:"bytes,1,opt,name=rack_name,json=rackName,proto3" json:"rack_name,omitempty"`
	Health    DesiredHealth     `protobuf:"varint,2,opt,name=health,proto3,enum=monitor.DesiredHealth" json:"health,omitempty"`
	LastStart *common.Timestamp `protobuf:"bytes,3,opt,name=last_start,json=lastStart,proto3" json:"last_start,omitempty"`
	// Types that are valid to be assigned to Details:
	//	*DesiredItem_Blade
	//	*DesiredItem_Pdu
	//	*DesiredItem_Tor
	Details              isDesiredItem_Details `protobuf_oneof:"details"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *DesiredItem) Reset()         { *m = DesiredItem{} }
func (m *DesiredItem) String() string { return proto.CompactTextString(m) }
func (*DesiredItem) ProtoMessage()    {}
func (*DesiredItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_318189739c1c4c20, []int{1, 3}
}

func (m *DesiredItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DesiredItem.Unmarshal(m, b)
}
func (m *DesiredItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DesiredItem.Marshal(b, m, deterministic)
}
func (m *DesiredItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DesiredItem.Merge(m, src)
}
func (m *DesiredItem) XXX_Size() int {
	return xxx_messageInfo_DesiredItem.Size(m)
}
func (m *DesiredItem) XXX_DiscardUnknown() {
	xxx_messageInfo_DesiredItem.DiscardUnknown(m)
}

var xxx_messageInfo_DesiredItem proto.InternalMessageInfo

func (m *DesiredItem) GetRackName() string {
	if m != nil {
		return m.RackName
	}
	return ""
}

func (m *DesiredItem) GetHealth() DesiredHealth {
	if m != nil {
		return m.Health
	}
	return Desired_Invalid
}

func (m *DesiredItem) GetLastStart() *common.Timestamp {
	if m != nil {
		return m.LastStart
	}
	return nil
}

type isDesiredItem_Details interface {
	isDesiredItem_Details()
}

type DesiredItem_Blade struct {
	Blade *DesiredBladeDetails `protobuf:"bytes,4,opt,name=blade,proto3,oneof"`
}

type DesiredItem_Pdu struct {
	Pdu *DesiredPduDetails `protobuf:"bytes,5,opt,name=pdu,proto3,oneof"`
}

type DesiredItem_Tor struct {
	Tor *DesiredTorDetails `protobuf:"bytes,6,opt,name=tor,proto3,oneof"`
}

func (*DesiredItem_Blade) isDesiredItem_Details() {}

func (*DesiredItem_Pdu) isDesiredItem_Details() {}

func (*DesiredItem_Tor) isDesiredItem_Details() {}

func (m *DesiredItem) GetDetails() isDesiredItem_Details {
	if m != nil {
		return m.Details
	}
	return nil
}

func (m *DesiredItem) GetBlade() *DesiredBladeDetails {
	if x, ok := m.GetDetails().(*DesiredItem_Blade); ok {
		return x.Blade
	}
	return nil
}

func (m *DesiredItem) GetPdu() *DesiredPduDetails {
	if x, ok := m.GetDetails().(*DesiredItem_Pdu); ok {
		return x.Pdu
	}
	return nil
}

func (m *DesiredItem) GetTor() *DesiredTorDetails {
	if x, ok := m.GetDetails().(*DesiredItem_Tor); ok {
		return x.Tor
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*DesiredItem) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*DesiredItem_Blade)(nil),
		(*DesiredItem_Pdu)(nil),
		(*DesiredItem_Tor)(nil),
	}
}

func init() {
	proto.RegisterEnum("monitor.ActualHealth", ActualHealth_name, ActualHealth_value)
	proto.RegisterEnum("monitor.DesiredHealth", DesiredHealth_name, DesiredHealth_value)
	proto.RegisterType((*Actual)(nil), "monitor.actual")
	proto.RegisterType((*ActualBladeDetails)(nil), "monitor.actual.blade_details")
	proto.RegisterType((*ActualPduDetails)(nil), "monitor.actual.pdu_details")
	proto.RegisterMapType((map[int64]bool)(nil), "monitor.actual.pdu_details.CablesEntry")
	proto.RegisterType((*ActualTorDetails)(nil), "monitor.actual.tor_details")
	proto.RegisterMapType((map[int64]bool)(nil), "monitor.actual.tor_details.CablesEntry")
	proto.RegisterType((*ActualItem)(nil), "monitor.actual.item")
	proto.RegisterType((*Desired)(nil), "monitor.desired")
	proto.RegisterType((*DesiredBladeDetails)(nil), "monitor.desired.blade_details")
	proto.RegisterType((*DesiredPduDetails)(nil), "monitor.desired.pdu_details")
	proto.RegisterMapType((map[int64]bool)(nil), "monitor.desired.pdu_details.CablesEntry")
	proto.RegisterType((*DesiredTorDetails)(nil), "monitor.desired.tor_details")
	proto.RegisterMapType((map[int64]bool)(nil), "monitor.desired.tor_details.CablesEntry")
	proto.RegisterType((*DesiredItem)(nil), "monitor.desired.item")
}

func init() {
	proto.RegisterFile("github.com/Jim3Things/CloudChamber/pkg/protos/monitor/monitor.proto", fileDescriptor_318189739c1c4c20)
}

var fileDescriptor_318189739c1c4c20 = []byte{
	// 719 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x95, 0xcd, 0x4e, 0xdb, 0x4a,
	0x14, 0xc7, 0x71, 0x3e, 0xc9, 0x31, 0x17, 0x7c, 0x47, 0x5c, 0xae, 0x65, 0xb8, 0xb7, 0x88, 0x4d,
	0x23, 0x2a, 0xd9, 0x51, 0x10, 0xa5, 0x1f, 0x8b, 0x56, 0x04, 0x24, 0x40, 0x6a, 0x2b, 0x39, 0x74,
	0xd3, 0x0d, 0x9a, 0xd8, 0x83, 0x33, 0xc2, 0xf6, 0x58, 0xe3, 0x71, 0xa4, 0x2c, 0xfa, 0x00, 0xe5,
	0x4d, 0xba, 0xe8, 0x7b, 0xf4, 0x65, 0xfa, 0x0e, 0xd5, 0xf8, 0x03, 0x39, 0x06, 0x02, 0xa5, 0x65,
	0x95, 0x78, 0xce, 0xff, 0x9c, 0xf3, 0x9f, 0x39, 0xbf, 0xd1, 0xc0, 0xc0, 0xa3, 0x62, 0x9c, 0x8c,
	0x4c, 0x87, 0x05, 0xd6, 0x09, 0x0d, 0x76, 0x4e, 0xc7, 0x34, 0xf4, 0x62, 0x6b, 0xe0, 0xb3, 0xc4,
	0x1d, 0x8c, 0x71, 0x30, 0x22, 0xdc, 0x8a, 0x2e, 0x3c, 0x2b, 0xe2, 0x4c, 0xb0, 0xd8, 0x0a, 0x58,
	0x48, 0x05, 0xe3, 0xc5, 0xaf, 0x99, 0x2e, 0xa3, 0x76, 0xfe, 0x69, 0xfc, 0x62, 0x35, 0x87, 0x05,
	0x01, 0x0b, 0x2d, 0x07, 0x47, 0xd8, 0xa1, 0x62, 0x9a, 0x55, 0x33, 0x0e, 0x1e, 0x54, 0x44, 0xd0,
	0x80, 0xc4, 0x02, 0x07, 0x51, 0x5e, 0x65, 0xdd, 0x63, 0xcc, 0xf3, 0x49, 0xa6, 0x1a, 0x25, 0xe7,
	0x16, 0x09, 0xa2, 0xa2, 0xc5, 0xd6, 0xf7, 0x16, 0xb4, 0xb0, 0x23, 0x12, 0xec, 0xa3, 0x6d, 0x68,
	0x52, 0x41, 0x82, 0x58, 0x57, 0x36, 0xeb, 0x5d, 0xb5, 0xbf, 0x6a, 0x16, 0x5b, 0xcb, 0xe2, 0xa6,
	0x0c, 0xda, 0x99, 0xc4, 0xf8, 0x0c, 0x7f, 0x8d, 0x7c, 0xec, 0x92, 0x33, 0x97, 0x08, 0x4c, 0xfd,
	0x18, 0x2d, 0x43, 0x8d, 0xba, 0xba, 0xb2, 0xa9, 0x74, 0xeb, 0x76, 0x8d, 0xba, 0xa8, 0x07, 0xed,
	0x88, 0x93, 0x98, 0x84, 0x42, 0xaf, 0x6d, 0x2a, 0x5d, 0xb5, 0xbf, 0x66, 0x66, 0xf6, 0xcc, 0x2c,
	0xaf, 0xd8, 0xa9, 0x5d, 0xc8, 0xd0, 0x36, 0x34, 0x92, 0x98, 0xb8, 0x7a, 0x7d, 0xae, 0x3c, 0xd5,
	0x18, 0x5f, 0x14, 0x50, 0x23, 0x37, 0xb9, 0xea, 0xfe, 0x06, 0x5a, 0x0e, 0x1e, 0xf9, 0xa4, 0xf0,
	0xfe, 0xb4, 0xea, 0xbd, 0x24, 0x36, 0x07, 0xa9, 0xf2, 0x30, 0x14, 0x7c, 0x6a, 0xe7, 0x69, 0xc6,
	0x4b, 0x50, 0x4b, 0xcb, 0x48, 0x83, 0xfa, 0x05, 0x99, 0xe6, 0xdb, 0x91, 0x7f, 0xd1, 0x2a, 0x34,
	0x27, 0xd8, 0x4f, 0x48, 0xba, 0x9b, 0x45, 0x3b, 0xfb, 0x78, 0x55, 0x7b, 0xa1, 0xa4, 0x5e, 0x04,
	0xe3, 0xf7, 0xf7, 0x52, 0x12, 0xff, 0x69, 0x2f, 0x5f, 0x6b, 0xd0, 0x90, 0x03, 0x42, 0xeb, 0xd0,
	0xe1, 0xd8, 0xb9, 0x38, 0x0b, 0x71, 0x40, 0xd2, 0xd4, 0x8e, 0xbd, 0x28, 0x17, 0xde, 0xe3, 0x80,
	0x20, 0x13, 0x5a, 0x63, 0x82, 0x7d, 0x31, 0x4e, 0x0b, 0x2c, 0xf7, 0xd7, 0xaa, 0x0e, 0xb3, 0xa8,
	0x9d, 0xab, 0x50, 0x0f, 0xc0, 0xc7, 0xb1, 0x38, 0x8b, 0x05, 0xe6, 0x22, 0x9f, 0xcf, 0xdf, 0xc5,
	0x7c, 0x4e, 0x0b, 0xda, 0xec, 0x8e, 0x14, 0x0d, 0xa5, 0x06, 0xed, 0x42, 0x33, 0x9d, 0x9b, 0xde,
	0x48, 0xc5, 0xff, 0x55, 0x1b, 0xcc, 0xb0, 0x73, 0xb4, 0x60, 0x67, 0x6a, 0x64, 0x41, 0x3d, 0x72,
	0x13, 0xbd, 0x99, 0x26, 0xad, 0xcf, 0x99, 0xe1, 0xd1, 0x82, 0x2d, 0x95, 0x32, 0x41, 0x30, 0xae,
	0xb7, 0x6e, 0x4e, 0x28, 0x1d, 0xb4, 0x4c, 0x10, 0x8c, 0xef, 0x77, 0xa0, 0x9d, 0xaf, 0x6c, 0x7d,
	0x28, 0x4e, 0x01, 0xa9, 0xd0, 0x3e, 0x0e, 0x27, 0xd8, 0xa7, 0xae, 0xb6, 0x80, 0x56, 0x40, 0xfd,
	0x18, 0xe2, 0x09, 0xa6, 0xbe, 0x9c, 0x81, 0xa6, 0xa0, 0x25, 0x58, 0x3c, 0xe0, 0x98, 0x86, 0x34,
	0xf4, 0xb4, 0x9a, 0xd4, 0x1e, 0xa5, 0x59, 0x53, 0xad, 0x2e, 0x43, 0x36, 0x09, 0xd8, 0x44, 0x86,
	0x1a, 0x5b, 0x3f, 0x9a, 0xb2, 0x78, 0x4c, 0x39, 0x71, 0xd1, 0xb3, 0xd9, 0xbb, 0xf4, 0xcf, 0x95,
	0xb5, 0x5c, 0x30, 0x73, 0x99, 0x9e, 0xdc, 0x71, 0x99, 0x8c, 0xcb, 0x0a, 0xee, 0x6f, 0x2b, 0x88,
	0x75, 0xaf, 0x95, 0x7f, 0x44, 0xde, 0x2f, 0x2b, 0xbc, 0xdf, 0x6d, 0xe6, 0x11, 0x81, 0xff, 0x76,
	0x2f, 0xe0, 0xad, 0x0a, 0xf0, 0xff, 0x5e, 0xb3, 0xf8, 0xdb, 0xc4, 0x3f, 0x9f, 0x25, 0xfe, 0xff,
	0x6b, 0x1d, 0x6e, 0x41, 0xbe, 0x57, 0x46, 0x7e, 0x63, 0xde, 0x1c, 0x0b, 0xe6, 0x7b, 0x65, 0xe6,
	0x37, 0xe6, 0x1d, 0xf6, 0x0d, 0xd0, 0x9f, 0xdc, 0x0c, 0x7d, 0x99, 0x71, 0x45, 0x86, 0x86, 0x82,
	0x45, 0x11, 0x71, 0xab, 0xc0, 0xab, 0xd0, 0x4e, 0x81, 0x27, 0xae, 0xd6, 0xe8, 0xef, 0x43, 0xfb,
	0x5d, 0xd6, 0x1c, 0xed, 0xc1, 0x92, 0x4d, 0x22, 0xc6, 0x45, 0x26, 0x45, 0x2b, 0x95, 0xab, 0x68,
	0xac, 0x99, 0xd9, 0x23, 0x64, 0x16, 0x8f, 0x90, 0x79, 0x28, 0x1f, 0xa1, 0xfe, 0x14, 0x3a, 0xc7,
	0xe1, 0x84, 0x84, 0x82, 0xf1, 0x29, 0x7a, 0x0d, 0x9d, 0x21, 0x11, 0x03, 0x16, 0x9e, 0x53, 0x0f,
	0xdd, 0x92, 0x71, 0x5b, 0x25, 0x64, 0x01, 0x0c, 0x89, 0x38, 0xc5, 0xdc, 0x23, 0x22, 0x46, 0x5a,
	0xf5, 0x5c, 0x8c, 0xaa, 0xa5, 0xfd, 0xbd, 0x4f, 0xbb, 0x0f, 0x7a, 0xf1, 0x47, 0xad, 0xf4, 0x7b,
	0xe7, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0x46, 0x3b, 0x56, 0x2b, 0x31, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MonitorClient is the client API for Monitor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MonitorClient interface {
	// Report the health of a set of inventory items to the monitor
	ReportHealth(ctx context.Context, in *Actual, opts ...grpc.CallOption) (*empty.Empty, error)
}

type monitorClient struct {
	cc *grpc.ClientConn
}

func NewMonitorClient(cc *grpc.ClientConn) MonitorClient {
	return &monitorClient{cc}
}

func (c *monitorClient) ReportHealth(ctx context.Context, in *Actual, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/monitor.Monitor/ReportHealth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MonitorServer is the server API for Monitor service.
type MonitorServer interface {
	// Report the health of a set of inventory items to the monitor
	ReportHealth(context.Context, *Actual) (*empty.Empty, error)
}

// UnimplementedMonitorServer can be embedded to have forward compatible implementations.
type UnimplementedMonitorServer struct {
}

func (*UnimplementedMonitorServer) ReportHealth(ctx context.Context, req *Actual) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportHealth not implemented")
}

func RegisterMonitorServer(s *grpc.Server, srv MonitorServer) {
	s.RegisterService(&_Monitor_serviceDesc, srv)
}

func _Monitor_ReportHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Actual)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServer).ReportHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/monitor.Monitor/ReportHealth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServer).ReportHealth(ctx, req.(*Actual))
	}
	return interceptor(ctx, in, info, handler)
}

var _Monitor_serviceDesc = grpc.ServiceDesc{
	ServiceName: "monitor.Monitor",
	HandlerType: (*MonitorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportHealth",
			Handler:    _Monitor_ReportHealth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/Jim3Things/CloudChamber/pkg/protos/monitor/monitor.proto",
}

// InventoryClient is the client API for Inventory service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InventoryClient interface {
	// Set the configuration options for reporting health
	SetConfig(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
	// Set the desired states for various inventory items.  Provide the
	// current actual state as informative return values.
	SetTargets(ctx context.Context, in *Desired, opts ...grpc.CallOption) (*Actual, error)
}

type inventoryClient struct {
	cc *grpc.ClientConn
}

func NewInventoryClient(cc *grpc.ClientConn) InventoryClient {
	return &inventoryClient{cc}
}

func (c *inventoryClient) SetConfig(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/monitor.Inventory/SetConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryClient) SetTargets(ctx context.Context, in *Desired, opts ...grpc.CallOption) (*Actual, error) {
	out := new(Actual)
	err := c.cc.Invoke(ctx, "/monitor.Inventory/SetTargets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InventoryServer is the server API for Inventory service.
type InventoryServer interface {
	// Set the configuration options for reporting health
	SetConfig(context.Context, *empty.Empty) (*empty.Empty, error)
	// Set the desired states for various inventory items.  Provide the
	// current actual state as informative return values.
	SetTargets(context.Context, *Desired) (*Actual, error)
}

// UnimplementedInventoryServer can be embedded to have forward compatible implementations.
type UnimplementedInventoryServer struct {
}

func (*UnimplementedInventoryServer) SetConfig(ctx context.Context, req *empty.Empty) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetConfig not implemented")
}
func (*UnimplementedInventoryServer) SetTargets(ctx context.Context, req *Desired) (*Actual, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetTargets not implemented")
}

func RegisterInventoryServer(s *grpc.Server, srv InventoryServer) {
	s.RegisterService(&_Inventory_serviceDesc, srv)
}

func _Inventory_SetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServer).SetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/monitor.Inventory/SetConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServer).SetConfig(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Inventory_SetTargets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Desired)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServer).SetTargets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/monitor.Inventory/SetTargets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServer).SetTargets(ctx, req.(*Desired))
	}
	return interceptor(ctx, in, info, handler)
}

var _Inventory_serviceDesc = grpc.ServiceDesc{
	ServiceName: "monitor.Inventory",
	HandlerType: (*InventoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetConfig",
			Handler:    _Inventory_SetConfig_Handler,
		},
		{
			MethodName: "SetTargets",
			Handler:    _Inventory_SetTargets_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/Jim3Things/CloudChamber/pkg/protos/monitor/monitor.proto",
}
