// Code generated by protoc-gen-go. DO NOT EDIT.
// source: log/entry.proto

package log

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Impact int32

const (
	Impact_Invalid Impact = 0
	Impact_Read    Impact = 1
	Impact_Create  Impact = 2
	Impact_Modify  Impact = 3
	Impact_Delete  Impact = 4
)

var Impact_name = map[int32]string{
	0: "Invalid",
	1: "Read",
	2: "Create",
	3: "Modify",
	4: "Delete",
}

var Impact_value = map[string]int32{
	"Invalid": 0,
	"Read":    1,
	"Create":  2,
	"Modify":  3,
	"Delete":  4,
}

func (x Impact) String() string {
	return proto.EnumName(Impact_name, int32(x))
}

func (Impact) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_62c9a8e672ec783e, []int{0}
}

type Module struct {
	Impact               Impact   `protobuf:"varint,1,opt,name=impact,proto3,enum=log.Impact" json:"impact,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Module) Reset()         { *m = Module{} }
func (m *Module) String() string { return proto.CompactTextString(m) }
func (*Module) ProtoMessage()    {}
func (*Module) Descriptor() ([]byte, []int) {
	return fileDescriptor_62c9a8e672ec783e, []int{0}
}

func (m *Module) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Module.Unmarshal(m, b)
}
func (m *Module) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Module.Marshal(b, m, deterministic)
}
func (m *Module) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Module.Merge(m, src)
}
func (m *Module) XXX_Size() int {
	return xxx_messageInfo_Module.Size(m)
}
func (m *Module) XXX_DiscardUnknown() {
	xxx_messageInfo_Module.DiscardUnknown(m)
}

var xxx_messageInfo_Module proto.InternalMessageInfo

func (m *Module) GetImpact() Impact {
	if m != nil {
		return m.Impact
	}
	return Impact_Invalid
}

func (m *Module) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Event struct {
	Tick                 int64     `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	Reason               string    `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Text                 string    `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Impacted             []*Module `protobuf:"bytes,4,rep,name=impacted,proto3" json:"impacted,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_62c9a8e672ec783e, []int{1}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetTick() int64 {
	if m != nil {
		return m.Tick
	}
	return 0
}

func (m *Event) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *Event) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Event) GetImpacted() []*Module {
	if m != nil {
		return m.Impacted
	}
	return nil
}

type Entry struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	SpanID               string   `protobuf:"bytes,2,opt,name=spanID,proto3" json:"spanID,omitempty"`
	ParentID             string   `protobuf:"bytes,3,opt,name=parentID,proto3" json:"parentID,omitempty"`
	Status               string   `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Event                []*Event `protobuf:"bytes,5,rep,name=event,proto3" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Entry) Reset()         { *m = Entry{} }
func (m *Entry) String() string { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()    {}
func (*Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_62c9a8e672ec783e, []int{2}
}

func (m *Entry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entry.Unmarshal(m, b)
}
func (m *Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entry.Marshal(b, m, deterministic)
}
func (m *Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entry.Merge(m, src)
}
func (m *Entry) XXX_Size() int {
	return xxx_messageInfo_Entry.Size(m)
}
func (m *Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_Entry.DiscardUnknown(m)
}

var xxx_messageInfo_Entry proto.InternalMessageInfo

func (m *Entry) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Entry) GetSpanID() string {
	if m != nil {
		return m.SpanID
	}
	return ""
}

func (m *Entry) GetParentID() string {
	if m != nil {
		return m.ParentID
	}
	return ""
}

func (m *Entry) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Entry) GetEvent() []*Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func init() {
	proto.RegisterEnum("log.Impact", Impact_name, Impact_value)
	proto.RegisterType((*Module)(nil), "log.module")
	proto.RegisterType((*Event)(nil), "log.event")
	proto.RegisterType((*Entry)(nil), "log.entry")
}

func init() { proto.RegisterFile("log/entry.proto", fileDescriptor_62c9a8e672ec783e) }

var fileDescriptor_62c9a8e672ec783e = []byte{
	// 277 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x51, 0xc1, 0x4e, 0x84, 0x30,
	0x14, 0xb4, 0x0b, 0x8b, 0xeb, 0x23, 0x51, 0xd2, 0x83, 0x69, 0x3c, 0x11, 0x3c, 0x48, 0x3c, 0x60,
	0xa2, 0x5f, 0x60, 0x96, 0x0b, 0x07, 0x2f, 0xfd, 0x83, 0xba, 0x3c, 0x09, 0xb1, 0xb4, 0x04, 0xba,
	0x1b, 0xf7, 0x13, 0xfc, 0x6b, 0xc3, 0x6b, 0x17, 0x6f, 0x33, 0x6f, 0x3a, 0x9d, 0x79, 0x2d, 0xdc,
	0x69, 0xdb, 0xbd, 0xa0, 0x71, 0xd3, 0xb9, 0x1a, 0x27, 0xeb, 0x2c, 0x8f, 0xb4, 0xed, 0x8a, 0x77,
	0x48, 0x06, 0xdb, 0x1e, 0x35, 0xf2, 0x47, 0x48, 0xfa, 0x61, 0x54, 0x07, 0x27, 0x58, 0xce, 0xca,
	0xdb, 0xd7, 0xb4, 0xd2, 0xb6, 0xab, 0xfc, 0x48, 0x06, 0x89, 0x73, 0x88, 0x8d, 0x1a, 0x50, 0x6c,
	0x72, 0x56, 0xde, 0x48, 0xc2, 0xc5, 0x08, 0x5b, 0x3c, 0xa1, 0x21, 0xd1, 0xf5, 0x87, 0x6f, 0xf2,
	0x47, 0x92, 0x30, 0xbf, 0x87, 0x64, 0x42, 0x35, 0x5b, 0x13, 0x2c, 0x81, 0xd1, 0x59, 0xfc, 0x71,
	0x22, 0xf2, 0x17, 0x2d, 0x98, 0x3f, 0xc1, 0xce, 0xc7, 0x60, 0x2b, 0xe2, 0x3c, 0x2a, 0xd3, 0xd0,
	0xc1, 0x17, 0x94, 0xab, 0x58, 0xfc, 0x32, 0xd8, 0xd2, 0x26, 0x6b, 0x1f, 0xf6, 0xdf, 0x67, 0x89,
	0x9c, 0x47, 0x65, 0x9a, 0xfa, 0x12, 0xe9, 0x19, 0x7f, 0x80, 0xdd, 0xa8, 0x26, 0x34, 0xae, 0xa9,
	0x43, 0xec, 0xca, 0xc9, 0xe3, 0x94, 0x3b, 0xce, 0x22, 0x0e, 0x1e, 0x62, 0x3c, 0x0f, 0xbb, 0x89,
	0x2d, 0xf5, 0x01, 0xea, 0x43, 0x13, 0xe9, 0x85, 0xe7, 0xfd, 0xe5, 0xd9, 0x78, 0x0a, 0xd7, 0x8d,
	0x39, 0x29, 0xdd, 0xb7, 0xd9, 0x15, 0xdf, 0x41, 0x2c, 0x51, 0xb5, 0x19, 0xe3, 0x00, 0xc9, 0x7e,
	0x42, 0xe5, 0x30, 0xdb, 0x2c, 0xf8, 0xc3, 0xb6, 0xfd, 0xd7, 0x39, 0x8b, 0x16, 0x5c, 0xa3, 0x46,
	0x87, 0x59, 0xfc, 0x99, 0xd0, 0x8f, 0xbc, 0xfd, 0x05, 0x00, 0x00, 0xff, 0xff, 0xd8, 0xa9, 0x8f,
	0xe4, 0xa4, 0x01, 0x00, 0x00,
}
