// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/Jim3Things/CloudChamber/pkg/protos/log/entry.proto

package log

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Describe the type of impact that this event has on a module.
type Impact int32

const (
	Impact_Invalid Impact = 0
	Impact_Read    Impact = 1
	Impact_Create  Impact = 2
	Impact_Modify  Impact = 3
	Impact_Delete  Impact = 4
	Impact_Execute Impact = 5
)

var Impact_name = map[int32]string{
	0: "Invalid",
	1: "Read",
	2: "Create",
	3: "Modify",
	4: "Delete",
	5: "Execute",
}

var Impact_value = map[string]int32{
	"Invalid": 0,
	"Read":    1,
	"Create":  2,
	"Modify":  3,
	"Delete":  4,
	"Execute": 5,
}

func (x Impact) String() string {
	return proto.EnumName(Impact_name, int32(x))
}

func (Impact) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_160789821e781b5c, []int{0}
}

// Describe an impacted module
type Module struct {
	Impact               Impact   `protobuf:"varint,1,opt,name=impact,proto3,enum=log.Impact" json:"impact,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Module) Reset()         { *m = Module{} }
func (m *Module) String() string { return proto.CompactTextString(m) }
func (*Module) ProtoMessage()    {}
func (*Module) Descriptor() ([]byte, []int) {
	return fileDescriptor_160789821e781b5c, []int{0}
}

func (m *Module) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Module.Unmarshal(m, b)
}
func (m *Module) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Module.Marshal(b, m, deterministic)
}
func (m *Module) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Module.Merge(m, src)
}
func (m *Module) XXX_Size() int {
	return xxx_messageInfo_Module.Size(m)
}
func (m *Module) XXX_DiscardUnknown() {
	xxx_messageInfo_Module.DiscardUnknown(m)
}

var xxx_messageInfo_Module proto.InternalMessageInfo

func (m *Module) GetImpact() Impact {
	if m != nil {
		return m.Impact
	}
	return Impact_Invalid
}

func (m *Module) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// Define an individual trace event
type Event struct {
	// Simulated time when it was logged.
	Tick int64 `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	// Annotation that describes why the event occurred.
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	// The event text itself.
	Text string `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	// The set of modules impacted, and the type of impact.
	Impacted             []*Module `protobuf:"bytes,4,rep,name=impacted,proto3" json:"impacted,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_160789821e781b5c, []int{1}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetTick() int64 {
	if m != nil {
		return m.Tick
	}
	return 0
}

func (m *Event) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *Event) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Event) GetImpacted() []*Module {
	if m != nil {
		return m.Impacted
	}
	return nil
}

// Describe a full correlated span, consisting of zero or more events.
type Entry struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	SpanID               string   `protobuf:"bytes,2,opt,name=spanID,proto3" json:"spanID,omitempty"`
	ParentID             string   `protobuf:"bytes,3,opt,name=parentID,proto3" json:"parentID,omitempty"`
	Status               string   `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Event                []*Event `protobuf:"bytes,5,rep,name=event,proto3" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Entry) Reset()         { *m = Entry{} }
func (m *Entry) String() string { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()    {}
func (*Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_160789821e781b5c, []int{2}
}

func (m *Entry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entry.Unmarshal(m, b)
}
func (m *Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entry.Marshal(b, m, deterministic)
}
func (m *Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entry.Merge(m, src)
}
func (m *Entry) XXX_Size() int {
	return xxx_messageInfo_Entry.Size(m)
}
func (m *Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_Entry.DiscardUnknown(m)
}

var xxx_messageInfo_Entry proto.InternalMessageInfo

func (m *Entry) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Entry) GetSpanID() string {
	if m != nil {
		return m.SpanID
	}
	return ""
}

func (m *Entry) GetParentID() string {
	if m != nil {
		return m.ParentID
	}
	return ""
}

func (m *Entry) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Entry) GetEvent() []*Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func init() {
	proto.RegisterEnum("log.Impact", Impact_name, Impact_value)
	proto.RegisterType((*Module)(nil), "log.module")
	proto.RegisterType((*Event)(nil), "log.event")
	proto.RegisterType((*Entry)(nil), "log.entry")
}

func init() {
	proto.RegisterFile("github.com/Jim3Things/CloudChamber/pkg/protos/log/entry.proto", fileDescriptor_160789821e781b5c)
}

var fileDescriptor_160789821e781b5c = []byte{
	// 332 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x51, 0x3f, 0x4f, 0xfb, 0x30,
	0x14, 0xfc, 0xa5, 0xf9, 0xf3, 0x2b, 0xaf, 0x12, 0x8a, 0x3c, 0xa0, 0x88, 0x29, 0x2a, 0x03, 0x15,
	0x43, 0x22, 0xe8, 0xcc, 0x00, 0x2d, 0x43, 0x91, 0x90, 0x50, 0xc4, 0xc4, 0xe6, 0x26, 0x8f, 0xd4,
	0xaa, 0x63, 0x47, 0x89, 0x53, 0xb5, 0x1f, 0x81, 0x6f, 0x8d, 0xf2, 0xe2, 0x86, 0x99, 0xed, 0xee,
	0x9d, 0xcf, 0x77, 0xcf, 0x86, 0xc7, 0x52, 0x98, 0x5d, 0xb7, 0x4d, 0x72, 0x5d, 0xa5, 0xaf, 0xa2,
	0x5a, 0x7e, 0xec, 0x84, 0x2a, 0xdb, 0x74, 0x25, 0x75, 0x57, 0xac, 0x76, 0xbc, 0xda, 0x62, 0x93,
	0xd6, 0xfb, 0x32, 0xad, 0x1b, 0x6d, 0x74, 0x9b, 0x4a, 0x5d, 0xa6, 0xa8, 0x4c, 0x73, 0x4a, 0x68,
	0xc0, 0x5c, 0xa9, 0xcb, 0xf9, 0x13, 0x04, 0x95, 0x2e, 0x3a, 0x89, 0xec, 0x06, 0x02, 0x51, 0xd5,
	0x3c, 0x37, 0x91, 0x13, 0x3b, 0x8b, 0xcb, 0x87, 0x59, 0x22, 0x75, 0x99, 0x0c, 0xa3, 0xcc, 0x4a,
	0x8c, 0x81, 0xa7, 0x78, 0x85, 0xd1, 0x24, 0x76, 0x16, 0x17, 0x19, 0xe1, 0x79, 0x0d, 0x3e, 0x1e,
	0x50, 0x91, 0x68, 0x44, 0xbe, 0x27, 0xbf, 0x9b, 0x11, 0x66, 0x57, 0x10, 0x34, 0xc8, 0x5b, 0xad,
	0xac, 0xc5, 0x32, 0x3a, 0x8b, 0x47, 0x13, 0xb9, 0xc3, 0x45, 0x3d, 0x66, 0xb7, 0x30, 0x1d, 0x62,
	0xb0, 0x88, 0xbc, 0xd8, 0x5d, 0xcc, 0x6c, 0x87, 0xa1, 0x60, 0x36, 0x8a, 0xf3, 0x6f, 0x07, 0x7c,
	0xda, 0x64, 0xec, 0xe3, 0xfc, 0xf6, 0xe9, 0x23, 0xdb, 0x9a, 0xab, 0xcd, 0xfa, 0x1c, 0x39, 0x30,
	0x76, 0x0d, 0xd3, 0x9a, 0x37, 0xa8, 0xcc, 0x66, 0x6d, 0x63, 0x47, 0x4e, 0x1e, 0xc3, 0x4d, 0xd7,
	0x46, 0x9e, 0xf5, 0x10, 0x63, 0xb1, 0xdd, 0x2d, 0xf2, 0xa9, 0x0f, 0x50, 0x1f, 0x9a, 0x64, 0x83,
	0x70, 0xf7, 0x7e, 0x7e, 0x36, 0x36, 0x83, 0xff, 0x1b, 0x75, 0xe0, 0x52, 0x14, 0xe1, 0x3f, 0x36,
	0x05, 0x2f, 0x43, 0x5e, 0x84, 0x0e, 0x03, 0x08, 0x56, 0x0d, 0x72, 0x83, 0xe1, 0xa4, 0xc7, 0x6f,
	0xba, 0x10, 0x5f, 0xa7, 0xd0, 0xed, 0xf1, 0x1a, 0x25, 0x1a, 0x0c, 0xbd, 0xde, 0xfa, 0x72, 0xc4,
	0xbc, 0x33, 0x18, 0xfa, 0xcf, 0xcb, 0xcf, 0xfb, 0x3f, 0x7f, 0xec, 0x36, 0x20, 0xbc, 0xfc, 0x09,
	0x00, 0x00, 0xff, 0xff, 0x1f, 0x5b, 0xc4, 0xaa, 0x14, 0x02, 0x00, 0x00,
}
