#defining a blade1 and blade2 for rack1
Racks:
  - Name: rack1
    Blades:
    - Index: 1
      Cores: 16
      MemoryInMb: 16834
      DiskInGb: 240 
      NetworkBandwidthInMbps: 2048
      Arch: "X64"
    - Index: 2
      Cores: 32
      MemoryInMb: 16834
      DiskInGb: 120
      NetworkBandwidthInMbps: 2048
      Arch: X64
    Tor:
    Pdu:
  - Name: rack2
    Blades:
    - Index: 1
      Cores: 16
      MemoryInMb: 16834
      DiskInGb: 240 
      NetworkBandwidthInMbps: 2048
      Arch: "X64"
    - Index: 2
      Cores: 8
      MemoryInMb: 16834
      DiskInGb: 120
      NetworkBandwidthInMbps: 2048
      Arch: X64
    Tor:
    Pdu:
  - Name: rack3
    Blades:
    - Index: 1
      Cores: 16
      MemoryInMb: 16834
      DiskInGb: 240 
      NetworkBandwidthInMbps: 2048
      Arch: "X64"
    - Index: 2
      Cores: 32
      MemoryInMb: 16834
      DiskInGb: 120
      NetworkBandwidthInMbps: 2048
      Arch: X64
    Tor:
    Pdu:
  - Name: rack4
    Blades:
    - Index: 1
      Cores: 16
      MemoryInMb: 16834
      DiskInGb: 240 
      NetworkBandwidthInMbps: 2048
      Arch: "X64"
    - Index: 2
      Cores: 32
      MemoryInMb: 16834
      DiskInGb: 120
      NetworkBandwidthInMbps: 2048
      Arch: X64
    Tor:
    Pdu:
  - Name: rack5
    Blades:
    - Index: 1
      Cores: 16
      MemoryInMb: 16834
      DiskInGb: 240 
      NetworkBandwidthInMbps: 2048
      Arch: "X64"
    - Index: 2
      Cores: 16
      MemoryInMb: 16834
      DiskInGb: 120
      NetworkBandwidthInMbps: 2048
      Arch: X64
    Tor:
    Pdu:
  - Name: rack6
    Blades:
    - Index: 1
      Cores: 16
      MemoryInMb: 16834
      DiskInGb: 240 
      NetworkBandwidthInMbps: 2048
      Arch: "X64"
    - Index: 2
      Cores: 32
      MemoryInMb: 16834
      DiskInGb: 120
      NetworkBandwidthInMbps: 2048
      Arch: X64
    Tor:
    Pdu:
  - Name: rack7
    Blades:
    - Index: 1
      Cores: 16
      MemoryInMb: 16834
      DiskInGb: 240 
      NetworkBandwidthInMbps: 2048
      Arch: "X64"
    - Index: 2
      Cores: 32
      MemoryInMb: 16834
      DiskInGb: 120
      NetworkBandwidthInMbps: 2048
      Arch: X64
    Tor:
    Pdu:
  - Name: rack8
    Blades:
    - Index: 1
      Cores: 16
      MemoryInMb: 16834
      DiskInGb: 240 
      NetworkBandwidthInMbps: 2048
      Arch: "X64"
    - Index: 2
      Cores: 32
      MemoryInMb: 16834
      DiskInGb: 120
      NetworkBandwidthInMbps: 2048
      Arch: X64
    Tor:
    Pdu: