// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/Jim3Things/CloudChamber/pkg/protos/admin/users.proto

package admin

import (
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// User is a representation of an individual user
//
// TODO This is just a placeholder until we have proper user records held
//     in a persisted store (Etcd)
//
type User struct {
	// The username, held so as to preserve the original case
	Name         string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PasswordHash []byte `protobuf:"bytes,2,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	UserId       int64  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Enabled      bool   `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// The rights this user has
	AccountManager       bool     `protobuf:"varint,5,opt,name=account_manager,json=accountManager,proto3" json:"account_manager,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_df38010c6a4bdd21, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetPasswordHash() []byte {
	if m != nil {
		return m.PasswordHash
	}
	return nil
}

func (m *User) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *User) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *User) GetAccountManager() bool {
	if m != nil {
		return m.AccountManager
	}
	return false
}

// Extend the base user definition with the revision number.  This is
// managed by the storage layer only, and is used as match criteria on
// updates.
type UserInternal struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Revision             int64    `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInternal) Reset()         { *m = UserInternal{} }
func (m *UserInternal) String() string { return proto.CompactTextString(m) }
func (*UserInternal) ProtoMessage()    {}
func (*UserInternal) Descriptor() ([]byte, []int) {
	return fileDescriptor_df38010c6a4bdd21, []int{1}
}

func (m *UserInternal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInternal.Unmarshal(m, b)
}
func (m *UserInternal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInternal.Marshal(b, m, deterministic)
}
func (m *UserInternal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInternal.Merge(m, src)
}
func (m *UserInternal) XXX_Size() int {
	return xxx_messageInfo_UserInternal.Size(m)
}
func (m *UserInternal) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInternal.DiscardUnknown(m)
}

var xxx_messageInfo_UserInternal proto.InternalMessageInfo

func (m *UserInternal) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *UserInternal) GetRevision() int64 {
	if m != nil {
		return m.Revision
	}
	return 0
}

// Limited exposure of user attributes for use when returning information
// to a remote client.
type UserPublic struct {
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// The rights this user has
	AccountManager       bool     `protobuf:"varint,2,opt,name=account_manager,json=accountManager,proto3" json:"account_manager,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserPublic) Reset()         { *m = UserPublic{} }
func (m *UserPublic) String() string { return proto.CompactTextString(m) }
func (*UserPublic) ProtoMessage()    {}
func (*UserPublic) Descriptor() ([]byte, []int) {
	return fileDescriptor_df38010c6a4bdd21, []int{2}
}

func (m *UserPublic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserPublic.Unmarshal(m, b)
}
func (m *UserPublic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserPublic.Marshal(b, m, deterministic)
}
func (m *UserPublic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserPublic.Merge(m, src)
}
func (m *UserPublic) XXX_Size() int {
	return xxx_messageInfo_UserPublic.Size(m)
}
func (m *UserPublic) XXX_DiscardUnknown() {
	xxx_messageInfo_UserPublic.DiscardUnknown(m)
}

var xxx_messageInfo_UserPublic proto.InternalMessageInfo

func (m *UserPublic) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *UserPublic) GetAccountManager() bool {
	if m != nil {
		return m.AccountManager
	}
	return false
}

// Public definition for a user, sent by a remote client to the Cloud Chamber
// controller.
type UserDefinition struct {
	Password string `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	Enabled  bool   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// The rights this user has
	AccountManager       bool     `protobuf:"varint,3,opt,name=account_manager,json=accountManager,proto3" json:"account_manager,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserDefinition) Reset()         { *m = UserDefinition{} }
func (m *UserDefinition) String() string { return proto.CompactTextString(m) }
func (*UserDefinition) ProtoMessage()    {}
func (*UserDefinition) Descriptor() ([]byte, []int) {
	return fileDescriptor_df38010c6a4bdd21, []int{3}
}

func (m *UserDefinition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserDefinition.Unmarshal(m, b)
}
func (m *UserDefinition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserDefinition.Marshal(b, m, deterministic)
}
func (m *UserDefinition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserDefinition.Merge(m, src)
}
func (m *UserDefinition) XXX_Size() int {
	return xxx_messageInfo_UserDefinition.Size(m)
}
func (m *UserDefinition) XXX_DiscardUnknown() {
	xxx_messageInfo_UserDefinition.DiscardUnknown(m)
}

var xxx_messageInfo_UserDefinition proto.InternalMessageInfo

func (m *UserDefinition) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UserDefinition) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *UserDefinition) GetAccountManager() bool {
	if m != nil {
		return m.AccountManager
	}
	return false
}

func init() {
	proto.RegisterType((*User)(nil), "admin.user")
	proto.RegisterType((*UserInternal)(nil), "admin.user_internal")
	proto.RegisterType((*UserPublic)(nil), "admin.user_public")
	proto.RegisterType((*UserDefinition)(nil), "admin.user_definition")
}

func init() {
	proto.RegisterFile("github.com/Jim3Things/CloudChamber/pkg/protos/admin/users.proto", fileDescriptor_df38010c6a4bdd21)
}

var fileDescriptor_df38010c6a4bdd21 = []byte{
	// 353 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0x4f, 0x4b, 0xc3, 0x30,
	0x18, 0xc6, 0x49, 0xdb, 0xfd, 0x31, 0xdb, 0x9c, 0xe4, 0x62, 0x99, 0x07, 0xcb, 0x76, 0xb0, 0x97,
	0x35, 0xe0, 0xf0, 0x2c, 0x6e, 0x17, 0x15, 0x05, 0x29, 0x9e, 0xbc, 0x8c, 0xb4, 0x89, 0x6d, 0xb0,
	0x4d, 0x4a, 0xd2, 0x4e, 0xf7, 0x7d, 0xfc, 0x94, 0x9e, 0xa4, 0xa9, 0x1b, 0x43, 0x07, 0x03, 0x6f,
	0x7d, 0x7e, 0x6d, 0x7f, 0xef, 0x93, 0x97, 0xc0, 0xeb, 0x84, 0x97, 0x69, 0x15, 0x05, 0xb1, 0xcc,
	0xf1, 0x3d, 0xcf, 0x67, 0xcf, 0x29, 0x17, 0x89, 0xc6, 0x8b, 0x4c, 0x56, 0x74, 0x91, 0x92, 0x3c,
	0x62, 0x0a, 0x17, 0x6f, 0x09, 0x2e, 0x94, 0x2c, 0xa5, 0xc6, 0x84, 0xe6, 0x5c, 0xe0, 0x4a, 0x33,
	0xa5, 0x03, 0x83, 0x50, 0xcb, 0xa0, 0xd1, 0xcd, 0x8e, 0x87, 0x89, 0x95, 0x5c, 0x17, 0x4a, 0x7e,
	0xac, 0x9b, 0xdf, 0xe2, 0x69, 0xc2, 0xc4, 0x74, 0x45, 0x32, 0x4e, 0x49, 0xc9, 0xf0, 0x9f, 0x87,
	0xc6, 0x34, 0xfe, 0x04, 0xd0, 0xa9, 0xcd, 0xe8, 0x0c, 0x3a, 0x82, 0xe4, 0xcc, 0x05, 0x1e, 0xf0,
	0x8f, 0xe6, 0x9d, 0xaf, 0xb9, 0xa3, 0xac, 0x13, 0x10, 0x1a, 0x88, 0x26, 0x70, 0x50, 0x10, 0xad,
	0xdf, 0xa5, 0xa2, 0xcb, 0x94, 0xe8, 0xd4, 0xb5, 0x3c, 0xe0, 0xf7, 0xc3, 0xfe, 0x06, 0xde, 0x12,
	0x9d, 0xa2, 0x53, 0xd8, 0xa9, 0x4d, 0x4b, 0x4e, 0x5d, 0xdb, 0x03, 0xbe, 0x1d, 0xb6, 0xeb, 0x78,
	0x47, 0x91, 0x0b, 0x3b, 0x4c, 0x90, 0x28, 0x63, 0xd4, 0x75, 0x3c, 0xe0, 0x77, 0xc3, 0x4d, 0x44,
	0x17, 0x70, 0x48, 0xe2, 0x58, 0x56, 0xa2, 0x5c, 0xe6, 0x44, 0x90, 0x84, 0x29, 0xb7, 0x65, 0xbe,
	0x38, 0xfe, 0xc1, 0x8f, 0x0d, 0x1d, 0x3f, 0xc0, 0x41, 0xe3, 0x16, 0x25, 0x53, 0x82, 0x64, 0xe8,
	0xbc, 0xa9, 0x6d, 0xea, 0xf6, 0x2e, 0x7b, 0x81, 0x59, 0x48, 0x50, 0xa3, 0xb0, 0x39, 0xcf, 0x08,
	0x76, 0x15, 0x5b, 0x71, 0xcd, 0xa5, 0x30, 0x6d, 0xed, 0x70, 0x9b, 0xc7, 0x4f, 0xb0, 0x67, 0x6c,
	0x45, 0x15, 0x65, 0x3c, 0xde, 0xed, 0x07, 0x0e, 0xf6, 0xb3, 0xf6, 0xf6, 0x5b, 0xc3, 0xa1, 0x31,
	0x52, 0xf6, 0xca, 0x05, 0x2f, 0xb9, 0x14, 0x68, 0x02, 0xbb, 0x9b, 0xf5, 0xfc, 0x5e, 0xea, 0xf6,
	0xc5, 0xee, 0x68, 0xeb, 0xe0, 0x68, 0x7b, 0xdf, 0xe8, 0xf9, 0xd5, 0xcb, 0xec, 0x1f, 0xd7, 0x29,
	0x6a, 0x9b, 0x34, 0xfb, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x14, 0x31, 0xcd, 0x73, 0x8c, 0x02, 0x00,
	0x00,
}
