name: build
on:
  pull_request:
jobs:
  golangci:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1' # The Go version to download (if necessary) and use.
      - uses: arduino/setup-protoc@master
      - uses: cedrickring/golang-action@1.5.2
        with:
          args: make build
