name: build
on:
  pull_request:
jobs:
  golangci:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: arduino/setup-protoc@master

      - name: build
        run: make build
