name: build
on:
  pull_request:
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.3

      - name: Install Protoc
        uses: arduino/setup-protoc@master

      - name: checkout
        uses: actions/checkout@v2

      - name: build
        run: |
          make build
